### ISSUE TITLE
Post to a Facebook Page

### ISSUE THREAD

**Issue by IngwiePhoenix** [SammyK/LaravelFacebookSdk#102]
My app has a public Facebook Page and whenever a moderator posts to the actual site's blog, I want to forward that to the Facebook Page as well.

Can I do that with this module?

**Comment by NightZpy** [comment]
+1
I agree post into facebook: group, personal account too!

**Comment by mryoaz** [comment]
It is possible to post to a Facebook Page. This is just a wrapper around de Facebook SDK.
See the Facebook API Docs.

You can start here for Facebook Pages:
https://developers.facebook.com/docs/pages/getting-started

**Comment by SammyK** [comment]
Thanks for the help on this one @mryoaz! :)
