### ISSUE TITLE
Foreign key constraint in Facebook login

### ISSUE THREAD

**Issue by lonAlbert** [SammyK/LaravelFacebookSdk#110]
I have a users table with a role_id foreign key. I need to assign a foreign key at the point:

`$user = App\User::createOrUpdateGraphNode($facebook_user);`

**Comment by SammyK** [comment]
Hey @lonAlbert! You can just save the relationships after the user is created:

```php
$user = App\User::createOrUpdateGraphNode($facebook_user);
$user->role_id = 123;
$user->save();
```
