### ISSUE TITLE
How to Use FB Notifications?

### ISSUE THREAD

**Issue by masterpowers** [SammyK/LaravelFacebookSdk#111]
I tried the sample from facebook PHP SDK 
but when i try to use $fb->api
api function doest not exist in the laravel php sdk
any work around on this?

**Comment by MirzaObaidSE** [comment]
Same problem with me i want to use search API but it is saying api not found
response = $fb->api('https://graph.facebook.com/search?q=john&type=user', '{user access token}');
error 
Call to undefined method SammyK\LaravelFacebookSdk\LaravelFacebookSdk::api()

**Comment by midi9x** [comment]
This is same problem with me. I also to use fb notification. Please help me if you used it. Thanks.

**Comment by MirzaObaidSE** [comment]
i have solved above problem 
$response = $fb->Get('/search?q=name to search&type=user','{user access token}'

**Comment by midi9x** [comment]
@masterpowers:  please help me using fb notification using LaravelFacebookSdk

**Comment by SammyK** [comment]
The `api()` method is from the old Facebook PHP SDK v3. This package ties into [v5 of the SDK](https://developers.facebook.com/docs/reference/php/).
