### ISSUE TITLE
Uncaught exception

### ISSUE THREAD

**Issue by ianzitow** [SammyK/LaravelFacebookSdk#113]
Hey, I'm having a very odd problem with exceptions. Here's my code:

`try {`
        `$response = $fb->get('/me?fields=id,email,first_name,last_name,gender', $accessToken);`
        `} catch (Facebook\Exceptions\FacebookResponseException $e) {`
            `response()->json(["error" => $e->getMessage());`
        `} catch (Facebook\Exceptions\FacebookSDKException $e) {`
            `response()->json(["error" => $e->getMessage()]);`
        `}`
        `$fb_user = $response->getGraphUser();`

For some reason, when I do have a FacebookResponseException, it tries to run the last line instead of just returning a JSON with the error attribute, which is not actually returned:

`ErrorException in AuthenticationController.php line 30:
Undefined variable: response`

Any ideas?

**Comment by SammyK** [comment]
You need to `return` your `response()`'s:

```php
return response()->json(["error" => $e->getMessage()]);
```

Or just:

```php
return ["error" => $e->getMessage()];
```

You're also missing a closing `]` in your `FacebookResponseException` catch block. :)
