### ISSUE TITLE
Multiple Edge requests 

### ISSUE THREAD

**Issue by juakali92** [SammyK/LaravelFacebookSdk#116]
I'm just wondering how i can make multiple graph requests eg.

$response_likes = $this->fb->get('/me?fields=likes{name},movies{id,name}');
$facebook_likes = $response_likes->getGraphEdge();

Do i use getGraphEdge here or Object? Constantly recieving errors when trying to achieve this.

Thanks

**Comment by SammyK** [comment]
The base request here is /me which is a UserNode. So you'll need to use `getGraphNode()` to pull the result and then access the likes via `getField('likes')`. Or you can convert the node to a plain-old array with `asArray()`. Hope that helps! :)
