### ISSUE TITLE
post video to facebook

### ISSUE THREAD

**Issue by garima-goyal** [SammyK/LaravelFacebookSdk#117]
hello,
I m using Sammyk/LaravelFacebookSdk in laravel 4.2. I need to post videos on facebook but not finding any way with it. 

Please help me out asap,

Thanks in advence

**Comment by SammyK** [comment]
Unfortunately this package isn't updated for Laravel 4.2 to use the latest Facebook PHP SDK v5 so video upload support is not trivial. You could install the Facebook PHP SDK v5 manually which has [built-in functionality for uploading videos](https://developers.facebook.com/docs/php/howto/example_upload_video).
