### ISSUE TITLE
Facebook Webhooks

### ISSUE THREAD

**Issue by mjp1** [SammyK/LaravelFacebookSdk#118]
Does this package support Facebook Webhooks (realtime updates)?

**Comment by SammyK** [comment]
You can subscribe to Webhooks with the [`/{app-id}/subscriptions`](https://developers.facebook.com/docs/graph-api/reference/v2.6/app/subscriptions/) endpoint using this package, but there's no direct support for Webhooks via custom functionality.

**Comment by obaid** [comment]
I am trying to get subscriptions to work but getting "Invalid Parameter" error. Here is the code if you can help me out that would be great.


`
try {
            $response = $fb->post(getenv('FACEBOOK_APP_ID')."/subscriptions", array(
                'object' => 'page',
                'callback_url' => 'http://mycallback_url/',
                'fields' => 'conversations',
                'verify_token' => 'test-token',
            ), $access_token);
        } catch(\Facebook\Exceptions\FacebookSDKException $e) {
            dd(['error' => $e->getMessage()]);
        }
`

I am following instructions on the parameters to be passed as outlined here: https://developers.facebook.com/docs/pages/realtime

Any idea what could be going wrong here?
