### ISSUE TITLE
Call to undefined method SammyK\LaravelFacebookSdk\FacebookFacade::get()

### ISSUE THREAD

**Issue by noprobz09** [SammyK/LaravelFacebookSdk#121]
Im getting error **Call to undefined method SammyK\LaravelFacebookSdk\FacebookFacade::get()**. I declare `use Facebook;` top on my controller and in the config/app, I put an alias `'Facebook'	=> 'SammyK\LaravelFacebookSdk\FacebookFacade',`. In my controller, I called it in this way `$response =  $this->facebook->get('/me?fields=id,name,email', $access_token);`. Im using L5.0, Is there a way to fix my issue? Thanks in advance :)

**Comment by noprobz09** [comment]
Nevermind, I able to solve it :)

**Comment by mugwag** [comment]
how did you solve this? I just loaded the package and have the same error. Was the "use" declaration wrong?

**Comment by noprobz09** [comment]
I just declare this `$fb = App::make('SammyK\LaravelFacebookSdk\LaravelFacebookSdk');` on the controllers constructor. Hope that helps :)

**Comment by mugwag** [comment]
Thank you! I actually added the declaration to my user model to get it working:

use SammyK\LaravelFacebookSdk\SyncableGraphNodeTrait;

class User extends Model
{
  use SyncableGraphNodeTrait; 
// ....
