### ISSUE TITLE
Redirect not working on windows safari and MAC Safari

### ISSUE THREAD

**Issue by nileshlets** [SammyK/LaravelFacebookSdk#123]
I using this package for facebook login. It is working fine in chrome and firefox in all os.
But in safari it is not working. Redirect from facebook is not working.

**Comment by SammyK** [comment]
Can you provide any error messages? And possibly snippets of code? :)

**Comment by nileshlets** [comment]
Hi,

I am not getting specific error code. But redirect is not working properly. This is common issue. You can read this issues.

zotonic/zotonic#902

intridea/omniauth-oauth2#72

Hope it may help. Thanks.

**Comment by SammyK** [comment]
Hey @nileshlets! Without any specific error messages or code snippets, it's not possible to figure out what's going wrong. I'm closing this but if you want to post some code here, that would help debug this issue better. :)

**Comment by johnef** [comment]
@nileshlets did you solve it
