### ISSUE TITLE
issue trying to get new token from Expired token

### ISSUE THREAD

**Issue by rainbowhat** [SammyK/LaravelFacebookSdk#124]
"Error validating access token: The session has been invalidated because the user has changed the password."
& 
"Error validating access token: Session does not match current stored session. This may be because the user changed the password since the time the session was created or Facebook has changed the session for security reasons."

How do i handle this two? Even if i re-loading and ask for new longlivedtoken & update the token(it's returning the same token), i still get this error.

I can login fine with this but the error is coming from PUBLISH ACTION

**Comment by SammyK** [comment]
You'll need to obtain an new access token from the user using the oAuth2 login flow. Facebook doesn't support refreshing tokens. Hope that helps! :)
