### ISSUE TITLE
How do I get timeline information?

### ISSUE THREAD

**Issue by illuminate3** [SammyK/LaravelFacebookSdk#125]
I'm trying to get the latest posts off my timeline for my site. How would I go about attacking this?

Do I have to login through Oauth to do this?

I tried most of the examples given and I end up with invalid oauth token or provide an access token?

I have signed up for my ID and Secret.

Thanks!

**Comment by jsrosas** [comment]
I have created a long lived token for my app, so I'm trying:
```
$session='long lived token from facebook'`
$request = Facebook::get(
$session, 'pageid'. 'feed');
$response = $request->execute();
$graphObject = $response->getGraphOject();
```
This works on the Graph API Explorer but I keep getting 
> Invalid OAuth access token. 

I am using the same token provided by facebook on both Graph API Explorer and Laravel.

**Comment by SammyK** [comment]
Hey @illuminate3!

> I'm trying to get the latest posts off my timeline for my site. How would I go about attacking this?

See the `/user/feed` endpoint: https://developers.facebook.com/docs/graph-api/reference/user/feed

> Do I have to login through Oauth to do this?

Yep! This lib should make all that easy though.

> I tried most of the examples given and I end up with invalid oauth token

Can you post any specific errors you're getting or relevant code snippets?


Hey @jsrosas! This really should be on a separate issue...

> I am using the same token provided by facebook on both Graph API Explorer and Laravel.

Make sure that the app you're using in your Laravel app matches the one in the Graph API Explorer. You should see a drop-down to select which app you want to use.

**Comment by jsrosas** [comment]
Yeah sorry I thought my code may help @illuminate3
