### ISSUE TITLE
Facebook redirect empty?

### ISSUE THREAD

**Issue by stephan-v** [SammyK/LaravelFacebookSdk#130]
Whenever I redirect back to my original page my url gets 

> #_=_

appended to it

Facebook claims to do this whenever a redirect_uri is empty but mine is actually set when I make a request to facebook. Is there any way to fix this behaviour?

**Comment by SammyK** [comment]
Hey @stephan-v! Are you speaking of the direct after the user authorizes your app in FB? That's something Facebook appends so there's not much you can do other than just redirect the user to a new URL after obtaining the access token.

**Comment by SammyK** [comment]
Ah, I see what you mean now. [Check this out](http://stackoverflow.com/questions/2286402/url-fragment-and-302-redirects)... seems like the only way to kill the hash is with hacky workarounds.
