### ISSUE TITLE
Closure function works in route but not in controller.

### ISSUE THREAD

**Issue by emil126a** [SammyK/LaravelFacebookSdk#131]
@SammyK My controller has following codes:
```

 <?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

class FacebookController extends Controller
{


	public function index(SammyK\LaravelFacebookSdk\LaravelFacebookSdk $fb)
	{
    // Send an array of permissions to request
		$login_url = $fb->getLoginUrl(['email']);
		return redirect()->away($login_url);
	}
}

```

And my route (web) has following lines:
`Route::get('/facebook/login', 'FacebookController@index');`

When I enter to 

> /facebook/login

I get 

> Class App\Http\Controllers\SammyK\LaravelFacebookSdk\LaravelFacebookSdk does not exist 

But it works perfectly if I just add following lines of code into web route. 

```
 Route::get('/facebook/login', function(SammyK\LaravelFacebookSdk\LaravelFacebookSdk $fb)
{
    // Send an array of permissions to request
    $login_url = $fb->getLoginUrl(['email']);


return redirect()->away($login_url);
 
});
```

How can I make it work with controller?

**Comment by david2alecs** [comment]
Hello @emil126a !

I thing you must add "use SammyK" in your controller.

`

<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

use SammyK;

class FacebookController extends Controller
{


    public function index(SammyK\LaravelFacebookSdk\LaravelFacebookSdk $fb)
    {
    // Send an array of permissions to request
        $login_url = $fb->getLoginUrl(['email']);
        return redirect()->away($login_url);
    }
}

`

**Comment by emil126a** [comment]
Thank you @david2alecs . It worked!

**Comment by david2alecs** [comment]
I'm glad I've been helpful.
