### ISSUE TITLE
video upload

### ISSUE THREAD

**Issue by wyklif** [SammyK/LaravelFacebookSdk#133]
Hi Sammy i love this package... i built an app long time ago using the laravel 4.2 branch which did not have the functionality to upload videos... is there a way that i can modify the 4.2 branch to upload videos? thanks

**Comment by SammyK** [comment]
Hey @wyklif! Glad you like the package! Unfortunately there isn't a good way to add video upload compatibility to the 4.2 branch. I hope you're eventually able to upgrade! :)

**Comment by wyklif** [comment]
i love the package i made my app in 4.2 and its too big 30+ controllers 30+ models 41 tables 100+ views i wont be able to port in the near future... but i can just delegate video uploading to the "raw" facebook php sdk right without the package?
