### ISSUE TITLE
Request User Permission to Post to their Facebook Wall

### ISSUE THREAD

**Issue by bunlongheng** [SammyK/LaravelFacebookSdk#134]
I'm trying to request my users for their permission to post to their facebook wall using [SammyK/LaravelFacebookSdk][1].

I have a button 

[![enter image description here][2]][2]

    <form method="POST" action="http://localhost:8888/facebook/checkin" accept-charset="UTF-8"><input name="_token" type="hidden" value="VTBcvupobSzcDThNeNguxCR4tMh2e28Wds4LzJA8">
      <button type="submit" id="check-in-with-facebook" class="btn btn-sm btn-primary btn-facebook">Check In</button>
    </form>

After, they clicked on it, this controller function will trigger 

    public function checkin(){
        $fb = App::make('SammyK\LaravelFacebookSdk\LaravelFacebookSdk');
        $permissions = 'publish_actions, user_posts, user_photos';
        $login_url = $fb->getLoginUrl(['email','scope'=>$permissions]);
        return redirect($login_url);
    }

Then, the redirect will happen to this URL below

    https://www.facebook.com/v2.5/dialog/oauth?redirect_uri=http%3A%2F%2Flocalhost%3A8888%2Ffacebook%2Flink&state=04c7d976a47fca8c370b08b9d1dd954d&scope=email%2Cmanage_pages%2Cpublish_pages%2C+publish_actions%2C+user_posts%2C+user_photos&response_type=code&client_id=956232267794396&ret=login&sdk=php-sdk-5.2.0&logger_id=aff4eaf6-269b-479a-a91c-aa53b57447d2&ext=1474663682&hash=AeYpZWVkApEd5u-N

Then, the modal will pop up, but I see only `Public Profile` and `Email Address`.

[![enter image description here][3]][3]

I requested for `publish_actions, user_posts, user_photos`

What did I do wrong ?  

Any suggestions / hints will be nice ... 

  [1]: https://github.com/SammyK/LaravelFacebookSdk
  [2]: http://i.stack.imgur.com/uROcn.png
  [3]: http://i.stack.imgur.com/MWPya.png

**Comment by david2alecs** [comment]
Hello @bunlongheng .

If you try with another account/user besides the main one, make sure you have added user to "Test Users" in your application.

**Comment by SammyK** [comment]
This line

```php
$permissions = 'publish_actions, user_posts, user_photos';
$login_url = $fb->getLoginUrl(['email','scope'=>$permissions]);
```

Should be:

```php
$login_url = $fb->getLoginUrl(['email', 'publish_actions', 'user_posts', 'user_photos']);
```

Good luck! :)
