### ISSUE TITLE
FacebookRequest for create event

### ISSUE THREAD

**Issue by nashowii** [SammyK/LaravelFacebookSdk#137]
hi guys, I come to you because I have a tremendous doubt. The need is I need to create events on Facebook, through my personal website. Then let me know where I find the FacebookRequest facebook makes reference.

I am working with the SKD sammyK to laravel, but I could not do this

Facebook asks this:

/ \* PHP SDK v5.0.0 \* /
/ \* Make the API call \* /
$ Request = new FacebookRequest (
   $ Session,
   'GET',
   '/ {Event-id}'
);
$ Response = $ request-> execute ();
$ GraphObject = $ response-> getGraphObject ();
/ \* Handle the result \* /

And the FacebookRequest not know where to get it, and others have all data.
Thanks and sorry for my English I am from Chile

Or any indication of how to create an event from a web in laravel

**Comment by SammyK** [comment]
Hey @nashowii! The code snippets on the Graph API reference pages documentation is all for version 4.0 of the PHP SDK even though it says v5.0.0 which is annoying. :/

Anyhow, [it's not possible to create events with the Graph API v2.x](http://stackoverflow.com/a/24499123/443479). Hope that helps! :)
