### ISSUE TITLE
i want to set default error language for facebook php sdk

### ISSUE THREAD

**Issue by shakir-appsys** [SammyK/LaravelFacebookSdk#138]
because i want to see error in english
like 

> Graph returned an error: URL-ul nu poate fi încărcat: Domeniul acestui URL nu este inclus în domeniile aplicaţiei. Pentru a putea încărca acest URL, adăugă toate domeniile şi subdomeniile aplicaţiei tale în câmpul Domeniile aplicaţiei din setăriile aplicaţiei tale.

**Comment by SammyK** [comment]
Hey @shakir-appsys! You can pass in the [`locale` parameter](https://developers.facebook.com/docs/graph-api/using-graph-api#readmodifiers) to get results for a specific locale.

- `?locale=de_DE` for German (Germany)
- `?locale=en_US` for English (USA)
- etc.
