### ISSUE TITLE
[Question] createOrUpdateGraphNode keeps setting the id of the model

### ISSUE THREAD

**Issue by computerfr33k** [SammyK/LaravelFacebookSdk#139]
I am trying to use the `createOrUpdateGraphNode()` method for creating/updating a user model. 
Here is my fillable_fields array:

``` php
protected static $graph_node_fillable_fields = [
        'name',
        'email',
    ];
```

Even though I tell it to only fill those fields, it keeps setting the user id to the facebook user id which is not what I want since I will store those details in another table since I will be having multiple oauth providers and to keep things organized.

**Comment by SammyK** [comment]
Hey @computerfr33k! Unfortunately this is a limitation of using `createOrUpdateGraphNode()`. It assumes that the unique index is based off the `id` field in the Graph node. As a feature it'd be nice to change this behavior to check for a unique index based on email or something else.

For now, I would suggest creating a new column for the Facebook node ID and setting up a [field mapping](https://github.com/SammyK/LaravelFacebookSdk#field-mapping) for it.
