### ISSUE TITLE
Handling failed to open stream: Network is unreachable

### ISSUE THREAD

**Issue by iggori** [SammyK/LaravelFacebookSdk#143]
Any idea how to handle in:
vendor/facebook/graph-sdk/src/Facebook/HttpClients/FacebookStream.php

ErrorException: file_get_contents(https://graph.facebook.com/v2.6/me?access_token=***************************&amp;appsecret_proof=***************&amp;fields=permissions): failed to open stream: Network is unreachable

Request was:
$request = $fb->get('/me?fields=permissions');

**Comment by SammyK** [comment]
Hey @iggori! Is sounds like you network wasn't able to access the Graph API. Feel free to chime in if you're still having an issue with this.

**Comment by iggori** [comment]
No we have no problem except when fb start crashing on weekends. I can send you logs from sentry or newrelic. This is not our fault facebook is sometimes not responsive and I think that we need to handle when there is no response for facebook because that happens too. Noone is perfect :)
