### ISSUE TITLE
User must be administrator (incorrect admin rights).

### ISSUE THREAD

**Issue by NicolasVanhecke** [SammyK/LaravelFacebookSdk#144]
FacebookResponseException in FacebookResponseException.php line 106:
The user must be an administrator of the page in order to impersonate it.

This is the error I am getting since the admin has moved and the website had a new developer (me). the feed worked before and I have no idea what else to try...
1. I am the administrator (one of 4) of the facebook page with my personal profile.
2. And I am also the owner of the facebook developers app. 
3. I have only changed the .env credentials (the faceboook_app_id and facebook_app_secret).

**Comment by SammyK** [comment]
Hey @NicolasVanhecke! If you're trying to post on behalf of a page, make sure you're using a page access token obtained from the [`/me/accounts` edge on the User node](https://developers.facebook.com/docs/graph-api/reference/user/accounts).
