### ISSUE TITLE
Installation fails on L5.3

### ISSUE THREAD

**Issue by crslp** [SammyK/LaravelFacebookSdk#151]
I'm quite sure this is my fault, since I am new to laravel. I apolpgize in advance.

I get an error when trying to make requests to the GraphAPI. I don't need Login or something, just API request.

I'm using PHP7.0.8, Laravel5.3 (not homestead). Both of these don't work.
// Directly from the IoC
$fb = App::make('SammyK\LaravelFacebookSdk\LaravelFacebookSdk');
// Or in PHP >= 5.5
$fb = app(SammyK\LaravelFacebookSdk\LaravelFacebookSdk::class);

The last one, gives me this error:
ReflectionException in Container.php line 749:
Class App\SammyK\LaravelFacebookSdk\LaravelFacebookSdk does not exist

More detailled screenshot: https://s28.postimg.org/ffk27jin1/error.jpg

Can you give me a hint or help how to resolve this?

**Comment by SammyK** [comment]
Hey @crslp! Try adding a `\` to the [class name reference](http://php.net/manual/en/language.namespaces.rules.php):

```php
$fb = app(\SammyK\LaravelFacebookSdk\LaravelFacebookSdk::class);
```

**Comment by crslp** [comment]
Thanks for your reply! 
That resolved my error, what a simple solution.
Right now, I wouldn't be able to find this by myself. Thanks again!
