### ISSUE TITLE
help!! why my response alway show "Unauthorized action."?

### ISSUE THREAD

**Issue by sheguibo** [SammyK/LaravelFacebookSdk#162]
help!! why my response alway show "Unauthorized action."?

i was copy the document code,alway response "Unauthorized action."

how can i get the token?

**Comment by sheguibo** [comment]
help

**Comment by Thielo** [comment]
What Document? Please provide us with some code you tried, so somebody can recreate your problem.

**Comment by sheguibo** [comment]
this is my code，after i click  "Login in with Facebook",  alway response "Unauthorized action."
“
Route::get('/facebook/login', function(SammyK\LaravelFacebookSdk\LaravelFacebookSdk $fb) {
    $login_link = $fb
        ->getRedirectLoginHelper()
        ->getLoginUrl('http://localhost/facebook/callback', ['email', 'user_events']);

    echo '<a href="' . $login_link . '">Login in with Facebook</a>';
});


Route::get('/facebook/callback', function(SammyK\LaravelFacebookSdk\LaravelFacebookSdk $fb)
{

    // Obtain an access token.
    try {
        $token = $fb->getAccessTokenFromRedirect();

    } catch (Facebook\Exceptions\FacebookSDKException $e) {
        dd($e->getMessage());
    }

    // Access token will be null if the user denied the request
    // or if someone just hit this URL outside of the OAuth flow.
    if (! $token) {
        // Get the redirect helper
        $helper = $fb->getRedirectLoginHelper();
        if (! $helper->getError()) {
            abort(403, 'Unauthorized action.');
        }

        // User denied the request
        dd(
            $helper->getError(),
            $helper->getErrorCode(),
            $helper->getErrorReason(),
            $helper->getErrorDescription()
        );
    }

    if (! $token->isLongLived()) {
        // OAuth 2.0 client handler
        $oauth_client = $fb->getOAuth2Client();

        // Extend the access token.
        try {
            $token = $oauth_client->getLongLivedAccessToken($token);
        } catch (Facebook\Exceptions\FacebookSDKException $e) {
            dd($e->getMessage());
        }
    }

    $fb->setDefaultAccessToken($token);

    // Save for later
    Session::put('fb_user_access_token', (string) $token);

    // Get basic info on the user from Facebook.
    try {
        $response = $fb->get('/me?fields=id,name,email');
    } catch (Facebook\Exceptions\FacebookSDKException $e) {
        dd($e->getMessage());
    }

    // Convert the response to a `Facebook/GraphNodes/GraphUser` collection
    $facebook_user = $response->getGraphUser();

    // Create the user if it does not exist or update the existing entry.
    // This will only work if you've added the SyncableGraphNodeTrait to your User model.
    $user = App\User::createOrUpdateGraphNode($facebook_user);

    // Log the user into Laravel
    Auth::login($user);

    return redirect('/')->with('message', 'Successfully logged in with Facebook');
});
”

**Comment by SammyK** [comment]
Hey @sheguibo! Make sure your app ID and app secret in the config match what you see in the [app dashboard](https://developers.facebook.com/apps). Also make sure the "Site URL" in the app settings is set to "http://localhost/".
