### ISSUE TITLE
Numeric value out of range

### ISSUE THREAD

**Issue by rafalradomski** [SammyK/LaravelFacebookSdk#166]
Hi I'm using code from lib doc (framework Laravel 5.1):

`$table->bigInteger('facebook_user_id')->unsigned()->index();`

when I run migration I getting error:

`SQLSTATE[22003]: Numeric value out of range: 167 Out of range value for column 'id' at row 1 (SQL: insert into `users` (`facebook_user_id`, `name`, `email`, `updated_at`, `created_at`) values (1452072323125376840, my name, my@email.com, 2017-04-18 21:53:26, 2017-04-18 21:53:26))`

I checked database and field exist:

facebook_user_id Indeks	bigint(20) UNSIGNED

any ideas how to fix it?

**Comment by rafalradomski** [comment]
Look like the mapping in my User model doesn't work, and it's trying save **facebook_user_id** in **id** field in my datebase, do you see something wrong here?

`namespace App;
use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use Zizaco\Entrust\Traits\EntrustUserTrait; // Entrust
use Cmgmyr\Messenger\Traits\Messagable; // Messanger
use SammyK\LaravelFacebookSdk\SyncableGraphNodeTrait;

class User extends Model implements AuthenticatableContract, CanResetPasswordContract {

    use Authenticatable, CanResetPassword, EntrustUserTrait, Messagable, SyncableGraphNodeTrait;

    // Facebook SDK
    protected static $graph_node_field_aliases = [
        'id' => 'facebook_user_id',
    ];`

**Comment by SammyK** [comment]
Hey @rafalradomski! Are you on a 32 bit system? If so, the [biggest unsigned int is 4294967295](https://en.wikipedia.org/wiki/32-bit) and the user ID you're trying to store is way bigger than that. I would try to store the user ID's in your database as an indexed VARCHAR instead of an unsigned big int. I hope that helps! :)

**Comment by rafalradomski** [comment]
Hi @SammyK I'm on 64-bit system windows 7, I'm using xampp v. 3.2.2.

I tried already tried few times to change fields **id** & **facebook_user_id** to VARCAHR wihout results

I think issue is with mapping value **id** to **facebook_user_id** it somehow ignore it and trying to save id in id field, and id is INT and AUTO_INCREMENT

I adding screenshot of my files and datebase, maybe you will find here something odd

![table](https://cloud.githubusercontent.com/assets/8066536/25253566/573dd5ea-2619-11e7-9799-84edc197526e.png)

![user1](https://cloud.githubusercontent.com/assets/8066536/25253673/d79543a4-2619-11e7-8a50-7c81848f9b06.png)
![user2](https://cloud.githubusercontent.com/assets/8066536/25253674/d79784f2-2619-11e7-8391-3f0028fdc889.png)
![facebook1](https://cloud.githubusercontent.com/assets/8066536/25253676/d79aa164-2619-11e7-90e3-6db827836949.png)
![faecbook2](https://cloud.githubusercontent.com/assets/8066536/25253675/d798c574-2619-11e7-99d0-2df94e938ae6.png)

**Comment by rafalradomski** [comment]
When I changed  **graph_node_field_aliases** to **protected static $facebook_field_aliases** in User Model the whole login process passing, but it's storing **facebook_user_id ** in **id** field and user it's not logged

![id](https://cloud.githubusercontent.com/assets/8066536/25255160/39859fb2-2621-11e7-909c-6b1babc74c4a.png)

**Comment by rafalradomski** [comment]
I tried latest version of laravel 5.4 and everything works.

@SammyK Are you sure that your library is still compatible with laravel 5.1 ?
