### ISSUE TITLE
Error posting Link

### ISSUE THREAD

**Issue by Creativohn** [SammyK/LaravelFacebookSdk#18]
friend

Firstly thank you for this great package for Laravel.

I have been reviewing the API documentation facebook and I face a serious mistake is that when I try to post a link through this package generates a FacebookQueryBuilderException me (10) error.

When I try to send only a single functioning properly post:

$status_update = array ('message' => 'Here Menssage');

But when I try to send a link debuelve me the error that you commented

$status_update = array ('link' => $ url, 'message' => 'Here Menssage');

FacebookQueryBuilderException (10).

I wonder where I am failing

$url = 'www.google.com';
Facebook::setAccessToken('Access-Token');	
$status_update = array('link' => $url, 'message' => 'Here Mensagge');
$response = Facebook::object('page_id/feed')->with($status_update)->post();

**Comment by SammyK** [comment]
Hey @Creativohn! Glad you're finding the package useful! :)

What is the specific error message being returned from `FacebookQueryBuilderException`? You can catch the error and display it like so:

```php
try {
    $response = Facebook::object('page_id/feed')->with($status_update)->post();
} catch (\SammyK\FacebookQueryBuilder\FacebookQueryBuilderException $e) {
    dd($e->getMessage());
}
```

Note that posting to a page might require [extended permissions](https://developers.facebook.com/docs/facebook-login/permissions/v2.2) like `manage_pages` & `post_actions` permissions.

Also when posting to the [`{page-id}/feed` endpoint](https://developers.facebook.com/docs/graph-api/reference/v2.2/page/feed/), you'll need to post a `message` **or** `link` param, but not both. If you're posting a `link` you can use the `description` param to customize the link preview description.

**Comment by Creativohn** [comment]
I put the code you provided tu me.
http://i.imgur.com/16IMKEq.png

and returning me on screen is:
http://i.imgur.com/im7PLv3.png

the application has permissions:
http://i.imgur.com/dfituqq.png

I still get the same error and do not know how to fix it, the package was running fine, but suddenly stopped working without any reason, every attempt I make is with a new security token generated on facebook console.

**Comment by SammyK** [comment]
Ah yes, can you change this line:

```php
dd($e->getMessage());
```

To this?

```php
dd($e->getPrevious()->getMessage());
```

That should return the error message that Graph is returning.

**Comment by Creativohn** [comment]
Thank you very much friend make the change and I could see what was the mistake, it was a permissions error, thank you very much!

**Comment by SammyK** [comment]
Oh excellent! Glad you figured it out! :)
