### ISSUE TITLE
summary() modifier not display in Array

### ISSUE THREAD

**Issue by sephXD** [SammyK/LaravelFacebookSdk#20]
Since I want to get fan page's post like_count,
I use the summary() modifier, but it's not display in the array.

Facebook::object("cnn/posts/")->fields('likes.limit(1).summary(true)')->get()->toArray();

**Comment by SammyK** [comment]
Hey @sephXD! You are correct that the summary cannot be accessed in v4.0 of the SDK. However in v4.1 the [summary value has a helper to access it](https://github.com/facebook/facebook-php-sdk-v4/pull/285). Unfortunately v4.1 hasn't been released yet, but it's close to release. If you'd like to get a head-start on the next release, the [4.1 documentation](https://github.com/facebook/facebook-php-sdk-v4/tree/master/docs) is almost up-to-date and [LaravelFacebookSdk v2](https://github.com/SammyK/LaravelFacebookSdk/tree/master) plays nicely with v4.1 of the SDK. :)
