### ISSUE TITLE
Still maintained ? 

### ISSUE THREAD

**Issue by Epistol** [SammyK/LaravelFacebookSdk#216]
Is the repo sleeping ? Last version of facebook sdk is 3.2 ^^'

**Comment by scottybo** [comment]
I'm guessing not - and according to the link below, none of the forks are actively maintained either: http://forked.yannick.io/SammyK/LaravelFacebookSdk

**Comment by rzelnik** [comment]
I would suggest to check this package:
https://github.com/vinkla/laravel-facebook
It's well maintained and updated, it just lacks more examples in the documentation.
