### ISSUE TITLE
Token still sometimes null from getTokenFromRedirect()

### ISSUE THREAD

**Issue by robertlagrant** [SammyK/LaravelFacebookSdk#22]
Sorry. Please don't get a court order or something against me asking so many questions :)

I've basically exactly copied your example code for logging in a user by Facebook. Here it is:

```php
	public function facebooklogin()
	{
		try
		{
			$token = Facebook::getTokenFromRedirect();
		
			if(!$token)
			{
				ob_start();
				var_dump(Input::all());
				$params = ob_get_contents();
				ob_end_clean();
				Log::error($params);
				return Redirect::to('/error')->with('error', '<!snip!> (Error 101)');
			}
            ...
```

At this point it hits that redirect and we're done. The error code was just so I knew at which point the error redirect happens. The log shows the redirect URL parameters look like this:

```
[2015-01-17 14:20:46] production.ERROR: array(2) {
  ["code"]=>
  string(323) "AQCHTNya-xzAc9eOgs7gD1RdgsG90Tgx_WqZvpTtoag99El8d27A7FsSKyUm6QfvU8eZcuQh6PPsselYemqqQ2dXHbPlP2gJknA949-75M5b1EXVaBJ7DgWymG6JHh6r9T7-STbVceTJqQNCSVTZ0NVBsn_aYTG852aMMFZS0fPgGli98X3hgzNdod4nZpJ4lBM2XOYtUPeyIsI780zP1lMy3wcxtmEeeHQVeC4LRWUkahqoOBfiQAawRDO27slChM3NdyIUvoj4JpINCv-RW-mw5IUe3RqruohlcXi9DoL34avGxoGwc7pUcFoW-SB6v14"
  ["state"]=>
  string(32) "611e655b35c625ea319b0c482a3810d5"
}
```

Which presumably means the token _wasn't_ empty. Am I missing something? Other than a clue? Or is it a bug? 

Final point: this has never happened to me when testing. It's happened to some people while testing, and (in what is probably a coincidence) they were using the built in Android browser on their phones.

**Update**: I logged the whole URL and there's nothing else to it; just code and state. Also, I assume this is correct, but this is the relevant part of the config:

```
'default_scope' => ['email'],
'default_redirect_uri' => '/facebook/login',
```

**Comment by SammyK** [comment]
Hey @robertlagrant! No worries - ask away! :)

You are correct, if the callback URL is receiving a `code` and `state`, those are the two things needed to validate the response and request an access token. So it looks like it was successful.

You mentioned that it was working fine when you were testing it. Did you make your Facebook app live? By default it will be in development mode until you explicitly make it public under your app dashboard & "status & review".

**Comment by robertlagrant** [comment]
Thanks :) Come to South Africa and we'll buy you a beer.

Yeah it's set to live, and various people I know (who aren't app admins) can register and use it successfully, on a variety of devices. However, some say they can't.

Some thoughts/observations: 
1) The user hits the first page, which detects they aren't logged in, and shows the log in with Facebook link. They click it. Because of the code listed above, which redirects them away as soon as it doesn't find a `$token`, they hit the error screen. Then they try hitting refresh, and it logs them in. Mind blown.
2) Why is it redirecting them away at the `if(!$token)` point if those variables are set? Is there a way this can be falsey even if both parameters are there?
3) I've set my mobile and site URLs to be exactly the same in Facebook's app config. Just in case that could be a problem. Also tried getting rid of the mobile URL because why not :) I've also set the app domain now.

Is there any other info I can provide that could be relevant to finding the problem? It seems very odd.

**Comment by SammyK** [comment]
Lol, we'll if I end up in South Africa sometime, I'll def try to hit you up! :)

Strange. How are you initially detecting if they are logged in or not? And how are you generating the log in link?

**Comment by robertlagrant** [comment]
The view (simplified):
```
@if(Auth::check()) 
    ... 
@else
    <p><a href="{{ route('login') }}"><img src="facebook.png" /></a></p>
@endif
```

Where the login route is specified like this:

routes.php:
```
Route::get('/login', array('uses' => 'LoginController@login','as' => 'login'));
```

LoginController.php:
```
public function login()
{
    if(Auth::check())     // just in case they visit this manually
    {
        return Redirect::route('user-profile');
    }
    else
    {
        return Redirect::to(Facebook::getLoginUrl());
    }
}
```

**Comment by SammyK** [comment]
Since the Facebook login status and the login status of your Laravel app are different, you can't rely on the fact that those two statuses will be in sync. So `Auth::check()` might return `true` since they could still be logged in with Laravel but the access token from Facebook might have already expired. For a little more info on this, check out the "_Managing The User's 'Logged In' State With The Web Framework_" header in this [Facebook login flow](https://www.sammyk.me/best-practice-for-facebook-login-with-the-javascript-sdk-and-php-sdk-v4-1) article.

For your particular case, is Facebook the only way you let users log in? If so, I'd base their logged-in status on whether or not they are logged into Facebook. This can be done most efficiently by using your existing code in tandem with the [JavaScript SDK](https://developers.facebook.com/docs/javascript).

**Comment by robertlagrant** [comment]
Ah okay,maybe that's it. Strange though that for some of these users I can delete their entry in the users table and they get the Log in with Facebook button, so they fail auth check, then they get the url back with state and code as logged in  my code, but it thinks $token is empty and sends them to the error page! Also when they hit refresh, they see the logged in screen, which also blows my mind.

Anyway. I can try the JS framework, though it seems weird that the two logged in states wouldn't line up without it.

They currently can only log in via facebook, but was thinking of adding a site-based login by just having a site login button as well as a log in with Facebook one if they failed auth check.

**Comment by robertlagrant** [comment]
Just realised something, having read your very nice article - I'm storing the access token against the user in the database, which your article says not to do. This (broken record time) doesn't explain why a new user would get an error, but I wonder if it's causing some weird mismatch. Do I need to bother with saving it, or does the sample login code get a new one every time anyway? Or is that only for the new version of the API?

**Comment by SammyK** [comment]
Yeah, there might be an issue with the login flow you've got going on. I just posted a [response comment on my blog](https://www.sammyk.me/access-token-handling-best-practices-in-facebook-php-sdk-v4#comment-1813153440) that is related to this issue, it might help you out a bit:

> The important thing to know about the FacebookJavascriptLoginHelper is that it is not making any calls to the Graph API to obtain a new token. It is simply reading from the cookie that the JS SDK set on your site. So once a user is logged in with the JS SDK, PHP will be able to grab the access token from the cookie the JS SDK set using the FacebookJavascriptLoginHelper on the next page request.

> I usually log a user in with the JS SDK and then redirect them with JS to a callback URL on my server that uses the FacebookJavascriptLoginHelper to grab the access token and exchange it for a long-lived access token. Then I save the long-lived access token in a PHP session and mark the user as "logged in" in my web framework.

> That way in PHP I can just make calls to the Graph API using the access token I've stored in the PHP session.

In general you don't need to store the access token in the database unless you're planning on making calls on behalf of the user when they are not logged into your app (like a 3AM CRON job or something). 

I like to store long-lived access tokens in a PHP session when the user is logged in. Every time they come back to the site they need to click the "login with Facebook" button again to go through the whole process of logging in with the JS SDK, redirecting to the callback URL that makes a long-lived access token & stores it in a session and marks the user as "logged in" in Laravel.

Hope that helps!

**Comment by robertlagrant** [comment]
Thanks, yes that's where my thoughts are going as well. When you say PHP session, do you use a Laravel session instead when working with Laravel?

Also, do you know why (even with storing the token in the DB; I don't think it was ever used) that `$token` would return as falsy? It feels as though there's some bug behind that somewhere.

**Comment by SammyK** [comment]
> do you use a Laravel session instead when working with Laravel

I just referred to it as a "PHP session" to disambiguate from the `FacebookSession` class in the PHP SDK 4.0 which has nothing to do with PHP sessions. :) So you can just use the native Laravel session handler.

> do you know why [...] $token would return as falsy?

The `Facebook::getTokenFromRedirect()` method is just a wrapper for the [native PHP SDK's `FacebookRedirectLoginHelper::getSessionFromRedirect()`](https://github.com/facebook/facebook-php-sdk-v4/blob/4.0-dev/src/Facebook/FacebookRedirectLoginHelper.php#L169). The wrapper will convert the response (either a `FacebookSession` or `null`) into an instance of `AccessToken` or `null`.

The method will return `null` if a `code` param doesn't exist on the callback URL, or the `state` param is missing or is not equal to the CSRF value that was generated by the SDK (and stored in a session).

So without seeing more of your code, I could suggest troubleshooting:

1) There's a problem generating the CSRF value that is set in the `state` param.
2) There's a problem storing the state value in the session.

Hope that helps!

**Comment by nitinbhujbal** [comment]
Hey hi,i was also suffering with same issue i solved it by modifying bit of got in function isValidRedirect() 
and it worked for me

I dont know whether it is right way or not but it did the trick :)

Here is the code from facbookredirectloginhelper

 protected function isValidRedirect()
  {
    $savedState = $this->loadState();
    if (!$this->getCode() || !isset($_GET['state'])) {
      return false;
    }
    $givenState = $_GET['state'];
    if(isset($_GET['state'])){
        $savedState = $givenState;
    }
    $savedLen = mb_strlen($savedState);
    $givenLen = mb_strlen($givenState);
    if ($savedLen !== $givenLen) {
      return false;
    }
    $result = 0;
    for ($i = 0; $i < $savedLen; $i++) {
      $result |= ord($savedState[$i]) ^ ord($givenState[$i]);
    }
    return $result === 0;
  }

**Comment by robertlagrant** [comment]
Nice, thanks. I was wondering about modifying that function, but couldn't work out what was needed in time. I'll experiment at some point and give feedback :)
