### ISSUE TITLE
Not able to use Facebook facade

### ISSUE THREAD

**Issue by vipulmehta13** [SammyK/LaravelFacebookSdk#23]
Not sure if its just me or for everyone...
I am not able to use "Facebook" facade.
I added alias and provider entry in my app.php, created proper configs as per readme file.
Please help if there is a known issue or something missing in readme or its just me :(

**Comment by jbrooksuk** [comment]
Have you ran `php artisan du`?

**Comment by SammyK** [comment]
If @jbrooksuk's suggestion doesn't work, which version of LaravelFacebookSdk are you using? And what error message are you getting?

**Comment by vipulmehta13** [comment]
Thanks for the responses... 
php artisan du did not work. I did run them before
php artisan dump-autoload --verbose

I am using "sammyk/laravel-facebook-sdk": "~1.1". Followed instructions as per the readme. Refreshed autoload

Code:
```php
<?php

session_start();
date_default_timezone_set('UTC');
require '/var/www/CA/vendor/autoload.php';
use Facebook;

Facebook :: setAppCredentials('xxxxxxxxx', 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx');
?>
```
Log:
[Wed Jan 21 11:55:09 2015] [error] [client xxx.xx.xxx.xxx] PHP Warning:  The use statement with non-compound name 'Facebook' has no effect in /var/www/CA/work/fb.php on line 6
[Wed Jan 21 11:55:09 2015] [error] [client xxx.xx.xxx.xxx] PHP Fatal error:  Class 'Facebook' not found in /var/www/CA/work/fb.php on line 9

**Comment by vipulmehta13** [comment]
My Bad !!! I have been using  version 1.1 not the newer version. Will try newer version and close the issue.
Sorry for the trouble..

**Comment by vipulmehta13** [comment]
I tried both the versions 1.1.1 and 1.1.2. It doesn't seem to work. Below are the steps I followed:

composer require "sammyk/laravel-facebook-sdk:1.1.1"
vi app/config/app.php
php artisan config:publish sammyk/laravel-facebook-sdk
php artisan du
php artisan dump-autoload --verbose
composer dump-autoload

Got the same error while running same code in the above comment.
Please help !!!

**Comment by jbrooksuk** [comment]
You need to do:

```php
use SammyK\LaravelFacebookSdk\FacebookFacade;
```

Not just `Facebook`?

**Comment by vipulmehta13** [comment]
I did try that last time..Its not able to utilize the underlying functions.

[error] [client xxxxxxxx] PHP Fatal error:  Call to a member function setAppCredentials() on a non-object in /var/www/CA/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 211

**Comment by jbrooksuk** [comment]
I think the problem here is how you're using it. That demo script, is it within a Laravel application? You shouldn't be including the Facade here if it's aliased.

**Comment by vipulmehta13** [comment]
Yes its with in Laravel application and aliased.

**Comment by SammyK** [comment]
Hey @vipulmehta13 - the code you posted above shouldn't work as it's not within the context of a Laravel app. And you shouldn't need to run `Facebook::setAppCredentials()` if you [published the config file](https://github.com/SammyK/LaravelFacebookSdk#configuration-file) and input your app id & secret in the generated config file.

Try putting the code in a test route in your `app/routes.php` file like so:

```php
Route::get('/fb-test', function () {
    $login_link = Facebook::getLoginUrl();
    dd($login_link);
});
```

Then visit `/fb-test` in your browser and see if the login link is displayed.

@jbrooksuk - thanks for helping with this one! :)

**Comment by jbrooksuk** [comment]
:beers:

**Comment by vipulmehta13** [comment]
Thanks

**Comment by jbrooksuk** [comment]
:)
