### ISSUE TITLE
Error when extending access token

### ISSUE THREAD

**Issue by prullenbak** [SammyK/LaravelFacebookSdk#24]
Hi, 

I'm trying to use this package, and I need to get a long lived access token. However, when I call $token->extend(), I get an error:

Exception 'Facebook\FacebookSDKException' with message 'You must provide or set a default application secret.'

It seems that in AccessToken.php, in the extend method, this array is not correctly filled.

$params = [
                'client_id' => Connection::$app_id,
                'client_secret' => Connection::$app_secret,
                'grant_type' => 'fb_exchange_token',
                'fb_exchange_token' => $this->access_token,
            ];

When I dump $params there, 'client_id' and 'client_secret' are null, which seems to be the reason for the error. 

How can I fix this? 

Thanks!

**Comment by SammyK** [comment]
How are you obtaining the access token? Can you provide the snippet of code that's causing the error?

Are you able to see the config if you do:

```php
dd(\Config::get('laravel-facebook-sdk::app_id'), \Config::get('laravel-facebook-sdk::app_secret'));
```

**Comment by prullenbak** [comment]
Thanks for the fast response!

If I use that code, it returns the values I entered in the config file (as expected).

I get the token just like in your example code and then store it in a session. 
```php
try{
     $token = Facebook::getTokenFromRedirect($redirect_uri);
     if (!$token) {
		return Redirect::to('/')->with('error', 'Unable to obtain access token.');
	}
}
catch (SammyK\FacebookQueryBuilder\FacebookQueryBuilderException $e) {
      return Redirect::back()->with('error', $e->getPrevious()->getMessage());
}	
Session::put('FacebookAccessToken', $token);
```
Then on another route, I get it from the session and try to extend it. 
```php
$token = Session::get('FacebookAccessToken');
if (! $token->isLongLived()) {		       			
        $token = $token->extend();		   
 }
```
and it throws the error. 

However, It tried it like this:
```php
$token = Session::get('FacebookAccessToken');
Facebook::setAccessToken($token);
if (! $token->isLongLived()) {		       			
        $token = $token->extend();		   
}
```

And it doesn't throw the error. But 
```php
Facebook::setAccessToken($token);
if (! $token->isLongLived()) {		       			
        $token = $token->extend();		   	     
}
dd($token->isLongLived());
```

still dumps "false", so it seems it's not getting a long lived token either.

**Comment by SammyK** [comment]
I usually extend my access tokens right after I get a short-lived access token. Try `extend()`ing the token before storing into a session. Then store the newly-generated long-lived access token in the session. And since the access token is returned as a PHP object, you might want to cast it to a string before saving it to a session.

```php
Session::put('FacebookAccessToken', (string) $token);
```

Also, due to limitations of v4.0 of the SDK, the `isLongLived()` feature will always return `false` unless you grab the token info with `getInfo()` or get a long-lived token with `extend()` beforehand:

```php
$tokenInfo = $token->getInfo();

// This should work now...
if ( ! $token->isLongLived()) {
    $token = $token->extend();
}
```

Let me know if any of that helps! :)
