### ISSUE TITLE
Search method not working

### ISSUE THREAD

**Issue by NgugiJ** [SammyK/LaravelFacebookSdk#25]
I get the following error when i try to access call search on the facade
Call to undefined method SammyK\LaravelFacebookSdk\LaravelFacebookSdk::object() 
Does this mean  not all FQB methods are defined on the Laravel Facade

**Comment by SammyK** [comment]
Hey @NgugiJ! What version of LaravelFacebookSdk are you using?

The `search()` and `object()` methods are features of the [FacebookQueryBuilder](https://github.com/SammyK/FacebookQueryBuilder) which was removed as a dependency from LaravelFacebookSdk in version 2.0.

**Comment by NgugiJ** [comment]
I'm using version  ~1.1. So i guess i have to have to install explicitly require FQB in my  composer, right?

**Comment by SammyK** [comment]
No, version 1.1 should install FQB for you when you run `composer install`.

Can you post some of the code that is throwing the error?
