### ISSUE TITLE
Facebook app doesn't connect 

### ISSUE THREAD

**Issue by oaattia** [SammyK/LaravelFacebookSdk#26]
Hello, what is the configuration that can i use to connect ? 
i'm using for my app domain ( localhost ) and for the website url http://localhost, but the problem that when i try facebook throught the following error 

Given URL is not allowed by the Application configuration.: One or more of the given URLs is not allowed by the App's settings. It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains.

what do you recommend  ?

**Comment by SammyK** [comment]
You need to add the "website" platform to you Facebook app under your app dashboard and then click on "settings". Add the "http://localhost" URL and also add "localhost" under app domains and click save. That should do it. :)

**Comment by oaattia** [comment]
But i did that and redirect successfully but i get the following error " Unable to obtain access token from redirect " 

Note: i'm using the same example you provided

**Comment by oaattia** [comment]
ok thank you i for the problem , i need to add session_start() to the index.php file to start the session first

**Comment by SammyK** [comment]
That's weird. Laravel should handle the session stuff for you. Oh well. Glad you figured it out!
