### ISSUE TITLE
SammyK \ FacebookQueryBuilder \ FacebookQueryBuilderException (10)  Graph returned an error response. 

### ISSUE THREAD

**Issue by kuldeep1984** [SammyK/LaravelFacebookSdk#27]
When using the following code Laravel 4 fired an exception : 
        Facebook::setAppCredentials('########', '#############');
     
        // This access token will be used for all calls to Graph.
        Facebook::setAccessToken('ff5ab5e96377be16436c9f2fe751b4c3');

        // Get the logged in user's profile.
        $user = Facebook::object('me')->fields('id', 'email')->get();

Exeception - 
SammyK \ FacebookQueryBuilder \ FacebookQueryBuilderException (10)  Graph returned an error response.

**Comment by SammyK** [comment]
You need to catch the exception and examine the error that is being returned from the Graph API.

```php
try {
    $user = Facebook::object('me')->fields('id', 'email')->get();
} catch (\SammyK\FacebookQueryBuilder\FacebookQueryBuilderException $e) {
    dd($e->getPrevious()->getMessage());
}
```

**Comment by kuldeep1984** [comment]
Thanks, I can figure this out!! :)

**Comment by kuldeep1984** [comment]
One More Thing ->
If i create an Facebook App and wants  it to manage via my Laravel Application like ... Manage permission like "Post to Wall" etc. and fetch the Facebook App statistics like "Page List", "Like Count", COmments etc.

What will be the approach using this Package. Please Help.

**Comment by SammyK** [comment]
In Facebook, analytics are called "insights".

For a Facebook Page you'll need the `read_insights` permission and then you can get the [`/{page-id}/insights` endpoint](https://developers.facebook.com/docs/graph-api/reference/v2.2/page/insights). That will give you access to a ton of [insight metrics](https://developers.facebook.com/docs/graph-api/reference/v2.2/insights/).

For a Facebook app, you hit the [`/{app-id}/app_insights` endpoint](https://developers.facebook.com/docs/graph-api/reference/v2.2/app/app_insights).

An example:

```php
// Page insights
$response = Facebook::object('{page-id}/insights')->get();

// App insights
$response = Facebook::object('{app-id}/app_insights')
    ->fields('time', 'value')
    ->with(['period' => 'daily']) // this is how you send modifiers
    ->get();
```

**Comment by kuldeep1984** [comment]
I am able to fetch info Using the "Facebook::setAccessToken" by passing the short-term access token from facebook. But When I am using "getTokenFromRedirect" , it returns NULL.

I am using the following code in my controller ->

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
$config['callback_url'] = 'http://value-studio.com/studioSocial';
        $fqb = new FQB();
       try
{
    $token = $fqb->auth()->getTokenFromRedirect($config['callback_url']);
}
catch (FacebookQueryBuilderException $e)
{
    echo '<p>Error: ' . $e->getMessage() . "\n\n";
    echo '<p>Facebook SDK Said: ' . $e->getPrevious()->getMessage() . "\n\n";
    exit;
}

if ( ! $token)
{
    /**
     * No token returned. Show login link.
     */
    $scope = ['email', 'read_stream']; // Optional
    $login_url = $fqb->auth()->getLoginUrl($config['callback_url'], $scope);
    echo '<a href="' . $login_url . '">Log in with Facebook</a>';
    //exit;
}

echo '<h1>Returned AccessToken Object</h1>' . "\n\n";
var_dump($token);
exit;
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////



please Help. How to get access token?

**Comment by SammyK** [comment]
Is this the code that Facebook will redirect the user to after they click login? If so, what values exist in the params of the URL after Facebook redirects the user to this page? There should be a param called `code` and one called `state`.

**Comment by kuldeep1984** [comment]
yes it returns the following url after login - 

http://value-studio.com/studioSocial?code=AQB6iONxKOVF7H85_sTTQNMF7LG1S5loB-mX1n3Mm5CGsiuvH4hJRsuK4a8MoEmcxztc4-qZkq2VT7uNH5wiOvqxcSwJbEKJGGuo_efaial1ARbP1GGhp-Cq4RQhm4VVy-4BG78-VvAHCkiYRtxMvQZKYxQAaB4I3JbUHaUkYeOM9KcCjsUFV9xMQUhkCFz-l1D3cxVihVUsrhmkcsIJTEzZt1BnYDR0W3CO-Y8CZrJuKeQc9WMpAMxYYyFCJRDX7YPnvqOHO0NX6Z1_JdB9IcA5kfBGtt14TGixP6K3koRsshfuxCh7pUvR4iIAsXcKJ5V71sdyQTYSDoBL47UQbDf5&state=83effc5e933befadfe7c5263acbd3572#_=_

**Comment by SammyK** [comment]
This line:

```php
$fqb = new FQB();
```

Should be grabbing an instance of the LaravelFacebookSdk:

```php
$fqb = App::make('laravel-facebook-sdk');
```

**Comment by kuldeep1984** [comment]
Now error is throwing  -

Call to undefined method SammyK\LaravelFacebookSdk\LaravelAuthFacebook::getTokenFromRedirect()

**Comment by SammyK** [comment]
Change:

```php
$token = $fqb->auth()->getTokenFromRedirect($config['callback_url']);

// to:

$token = $fqb->getTokenFromRedirect($config['callback_url']);
```

And:

```php
$login_url = $fqb->auth()->getLoginUrl($config['callback_url'], $scope);

// to:

$login_url = $fqb->getLoginUrl($scope, $config['callback_url']);
```

**Comment by kuldeep1984** [comment]
well...now error is gone but Token returning NULL

**Comment by SammyK** [comment]
Did you publish the config file in your laravel app?

**Comment by kuldeep1984** [comment]
yes

**Comment by SammyK** [comment]
It sounds like there might be a problem with validating the state param which is CSRF protection. Maybe  a session issue.

For debugging, add these to your callback URL

```php
var_dump(Session::get('state'));
var_dump(Input::get('state'));
```

After you get redirected to the page after clicking login, those values should both be a random string and should both be the same value.

**Comment by kuldeep1984** [comment]
Yes. You are right. Everytime I clicked on the login URL. Both returns the different and random value

**Comment by SammyK** [comment]
Weird, I'm not sure why you're getting two different values. Are you calling `getLoginUrl()` any time before `getTokenFromRedirect()`? What code do you have before the `getTokenFromRedirect()` section?

**Comment by kuldeep1984** [comment]
Facebook::setAppCredentials('365767286936997', 'd7723387afdf0c6fbe61d6b7233c63e8');
  $config['callback_url'] = 'http://value-studio.com/studioSocial';
       $fqb = App::make('laravel-facebook-sdk');
       try
{
           $token = $fqb->getTokenFromRedirect($config['callback_url']);   
}
catch (FacebookQueryBuilderException $e)
{
    echo '<p>Error: ' . $e->getMessage() . "\n\n";
    echo '<p>Facebook SDK Said: ' . $e->getPrevious()->getMessage() . "\n\n";
    exit;
}

**Comment by SammyK** [comment]
Actually - are the two values different if you put that debug snippet just above the `if ( ! $token)` line?

**Comment by kuldeep1984** [comment]
the whole code is ->

  Facebook::setAppCredentials('365767286936997', 'd7723387afdf0c6fbe61d6b7233c63e8');
        $config['callback_url'] = 'http://value-studio.com/studioSocial';
       $fqb = App::make('laravel-facebook-sdk');
       try
{
           $token = $fqb->getTokenFromRedirect($config['callback_url']);   
}
catch (FacebookQueryBuilderException $e)
{
    echo '<p>Error: ' . $e->getMessage() . "\n\n";
    echo '<p>Facebook SDK Said: ' . $e->getPrevious()->getMessage() . "\n\n";
    exit;
}

if ( ! $token)
{
    /**
     * No token returned. Show login link.
     */
    $scope = ['email', 'read_stream']; // Optional
    $login_url = $fqb->getLoginUrl($scope,$config['callback_url']);
    echo '<a href="' . $login_url . '">Log in with Facebook</a>';
    //exit;
}

echo '<h1>Returned AccessToken Object</h1>' . "\n\n";
var_dump($token);
 var_dump(Session::get('state'));
 var_dump(Input::get('state'));

----------------------------------------------------

**Comment by SammyK** [comment]
Yeah, so move this:

```php
var_dump(Session::get('state'));
var_dump(Input::get('state'));
```

Above the `if ( ! $token)` line and try it again to see if the values are different. Right now the values will always be different since the call to `getLoginUrl()` above them will reset the state in the session.

**Comment by kuldeep1984** [comment]
Output - 
string(32) "0ab16f12036839c1389da805355c3c2e" 
NULL

**Comment by SammyK** [comment]
Add these lines after those debugging lines:

```php
var_dump(Input::get('error'));
var_dump(Input::get('error_reason'));
var_dump(Input::get('error_description'));
```

And try again

**Comment by kuldeep1984** [comment]
OUTPUT
string(32) "0ab16f12036839c1389da805355c3c2e" 
NULL 
NULL 
NULL 
NULL

**Comment by SammyK** [comment]
Is this the output after you click on the login link? That would be the expected output before you clicked on the login link and Facebook redirect you back to the URL. We want to see the output after you get redirected back from Facebook.

**Comment by kuldeep1984** [comment]
After clicking the "login link"
string(32) "0ab16f12036839c1389da805355c3c2e" 
string(32) "0dfd9cfb3e14e7b67353fd84d10d11c5" 
NULL
 NULL 
NULL

**Comment by SammyK** [comment]
Yeah, your `state` is definitely getting out of sync for some reason. This is either a bug or a misconfiguration in your code or on your hosting environment. I'll have to do some more research to see if I can replicate these results.

**Comment by SammyK** [comment]
I think what's happening here is that the `state` key is being overwritten somewhere else in your code. I've updated the LaravelFacebookSdk to version 1.3.0 which adds a prefix to prevent this issue. Go ahead and update and let me know if that fixes your issue! :)

**Comment by SammyK** [comment]
**Update:** Actually, that didn't fix it. Grrr. :( So it looks like there's something wonky going on with the `getLoginUrl()`. Sometimes it will generate a CSRF token twice and not save it to the session the second time. But since v1.x of this package depends on FQB and that depends on the Facebook PHP SDK v4.0 which is a pain in the butt to overwrite, I'm not sure how to fix this.

I've spent the past few hours on this and I'm about to just throw up my hands and say don't use the v1.x for "redirect login" stuff. You can still use it by logging a user in via JavaScript & then pulling in the access token. That's a lot more stable & a better UX anyways.

But version 2.x doesn't suffer from this problem and the code is far less complicated (no dependency on FQB & uses PHP SDK v4.1).

So sorry I couldn't save this one, but I'm going to mark this method as "unstable" for v1.x and hope you guys won't murder me. :/

**Comment by davout1806** [comment]
So will Laravel Facebook SDK 2.x work with Laravel 4?

Thanks.
