### ISSUE TITLE
Make sure it works on Laravel 5

### ISSUE THREAD

**Issue by SammyK** [SammyK/LaravelFacebookSdk#32]
Cause that's gonna be a thing like tomorrow or something...

**Comment by DaHaiz** [comment]
Hi Sammy,
can you say how long it will take until its laravel 5 ready? We're on starting a new project and would like to use laravel 5. We have a strong facebook connection to be built up and your package seems to be a very good choice. Of course we would help on making it laravel 5 compatible, if you provide us with information what has to be done. Sadly we have never used laravel before (coming from zend 1/2). Therefore we have no clue what's needed to make it work with laravel 5.

greets, dahaiz

**Comment by SammyK** [comment]
Hey @DaHaiz! I'm working on this this week. I'll let you know when it's ready. :)

**Comment by DaHaiz** [comment]
aah your're great man! much thanks! :)

**Comment by antonioribeiro** [comment]
+1 waiting for it too :)

Thank you!

**Comment by SammyK** [comment]
Hey guys - got this rocking last night on the master branch!

It's got [some BC's in it](https://github.com/SammyK/LaravelFacebookSdk/blob/master/CHANGELOG.md) and it's in dev mode until the Facebook PHP SDK v4.1 is officially tagged as stable. I'm going to close this issue out. If you run into any trouble with it, please let me know by submitting a new issue.

Good luck! :)

**Comment by antonioribeiro** [comment]
Wow! That was fast.
Can't wait to try it out on L5.
Cheers!
