### ISSUE TITLE
redirect to app page not the facebook app canvas 

### ISSUE THREAD

**Issue by oaattia** [SammyK/LaravelFacebookSdk#33]
Hello i have a problem and i would be happy if you helped me in it, i have a facebook page tab that we i click on connect i use your example to get the loggin data and redirect back to the website app , but what i want here to redirect to facebook app tab ( the canvas ) and be logged in the canvas also 

can i do that ? sorry for my bad english but any help would be appreciated

**Comment by SammyK** [comment]
Hey @oaattia!

In general you can grab the access token from the Page tab and store it in a session. Then you can redirect the user to the canvas version of your app. But you'll need to redirect them with JavaScript to bust them out of the Page tab iframe:

```javascript
window.top.location.href = "https://apps.facebook.com/your-app-namespace";
```

Hope that helps!
