### ISSUE TITLE
Class 'Facebook\FacebookSession' not found

### ISSUE THREAD

**Issue by 0x1AD2** [SammyK/LaravelFacebookSdk#36]
I recieved the following error installing different versions of the package trough composer: ` PHP Fatal error: Class 'Facebook\FacebookSession' not found in /sammyk\facebook-query-builder\src\Connection.php:82 ` 

I tried to install the following versions (also removed the whole vendor directory and cleared composers cache).

- 1.1.x-dev
- 1.1.2
- 1.1.1
- 1.1.0
- 1.0.0

Except for 1.0.0 none of them worked the way they should. I'm running that until there is a better solution.

- *I saw that it's a recurring issue: https://github.com/SammyK/LaravelFacebookSdk/issues/12*
- *In connection.php the `use` properties (for namespacing) where present.

**Comment by SammyK** [comment]
What are you using in your `composer.json` for the `require` field?

If you have [the `minimum-stability` flag](https://getcomposer.org/doc/04-schema.md#minimum-stability) set to `dev`, that could make things go wonky.

Specifically the LaravelFacebookSdk requires the FacebookQueryBuilder which requires the Facebook PHP SDK. And the early release erroneously pulled in the [`dev-master` branch](https://github.com/SammyK/FacebookQueryBuilder/commit/bbb1546e23a83cd447554ebf911c597a0f76cdea#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780L17) which does not have a `FacebookSession` hence the error.

On as side note, I'm working on getting v2 ready today which depends on just the Facebook PHP SDK which should make things a lot easier. :)

**Comment by 0x1AD2** [comment]
` ` `
	"require": {
	  	"laravel/framework": "4.2.*",
		"davejamesmiller/laravel-breadcrumbs": "2.3.0",
		"intervention/image-mod": "dev-master",
		"mews/purifier": "dev-master",
		"sunra/php-simple-html-dom-parser": "dev-master",
		"goodby/csv": "*",
		"roumen/sitemap": "dev-master",
		"philo/laravel-twitter": "dev-master",
		"sammyk/laravel-facebook-sdk": "1.0",
	  	"guzzlehttp/guzzle": "~4.0"
	},
` ` `

Yes I've the `minimum-stability`  flag set on `dev`  I think if I don't I might break a thing or two. I' ll ut it on ` stable` and update composer to see how that works out.

And I'm looking forward to v2 could you contact me when it's ready?

**Comment by SammyK** [comment]
Yeah, pulling from dev-master is a recipe for disaster. I'd recommend updating your `minimum-stability` to `stable` and changing all references to `dev-master` to the package's latest stable version.

I didn't push version 2 last night, but I did get an update rocking for v1.x.
