### ISSUE TITLE
How to create a new FacebookRequest?

### ISSUE THREAD

**Issue by 0x1AD2** [SammyK/LaravelFacebookSdk#37]
Sammy,

I've trouble with de-authorizing users, I want them to just disconnect their accounts by a press on the button. What I could find on Facebook was that there is a FacebookRequest method that lets you do stuff like that, is there also such a method available in your package?

```php
/* PHP SDK v4.0.0 */
/* make the API call */
$request = new FacebookRequest(
  $session,
  'DELETE',
  '/me/permissions'
);
$response = $request->execute();
$graphObject = $response->getGraphObject();
/* handle the result */
```

**Comment by SammyK** [comment]
Did you upgraded to Laravel 5? [I upgraded this package to use L5 last night](https://github.com/SammyK/LaravelFacebookSdk/blob/master/CHANGELOG.md). :)

For Laravel 5:

```php
// only need to pass access token if you didn't set a default
$response = $fb->delete('/me/permissions', 'access-token');
```

For Laravel 4.2:

```php
$response = $fb->object('me/permissions')->delete();
```

**Comment by 0x1AD2** [comment]
@SammyK I saw you updated the package, I haven't upgraded this application to L5 yet because I just updated it from 4.0 to 4.2 :smile:

Thanks for the examples and is there any place where these kind of methods are documentetated. And whats the $fb var? Could it also be achieved by using ` Facebook::object('me/permissions')->delete();`?

**Comment by 0x1AD2** [comment]
@SammyK I tried it and It could also be achieved by using :+1:  
```php
Facebook::object('me/permissions')->delete();
```
 (I had this line of code for quite a while) unfortunately I didn't work for so I created this issue, today I added the part of setting the access token and everything worked like charm.

```php
// get access token from session
$token = \Session::get('facebook_access_token');

// set the access token
\Facebook::setAccessToken($token);
```

**Comment by 0x1AD2** [comment]
@SammyK maybe you could point out the different ways to grabs instances from the IoC container in 4.2 the same as you did for the 5 version.

**Comment by SammyK** [comment]
Glad you figured it out!

Grabbing instances in 4.2 is limited to just:

```php
$fb = App::make('laravel-facebook-sdk');
```
