### ISSUE TITLE
Custom state parameter

### ISSUE THREAD

**Issue by threeel** [SammyK/LaravelFacebookSdk#38]
is there any way that i can create a custom state param on the getLoginurl...?
what i am trying to do is pass some parameters on the oauth request endpoint and get back the state.
the state to be base64 encoded of my parameters...
i dont know if what i am saying is valid with the facebooksdk v4.
thanks.

**Comment by SammyK** [comment]
The Facebook PHP SDK will generate a state param for you automatically. It's best to let it worry about generating it for you since it needs to be generated by a [CSPRNG](http://en.wikipedia.org/wiki/Cryptographically_secure_pseudorandom_number_generator).
