### ISSUE TITLE
when scope is set no callback is happening

### ISSUE THREAD

**Issue by threeel** [SammyK/LaravelFacebookSdk#39]
I am having a weird problem.
when i set up the 
```php
       default_scope=['email','public_profile'];
```
the callback from facebook is not happening.
i can login successful but no callback
i have tried setting it up on the 
```php
$this->fb->getLoginUrl(['email','public_profile'],'http://example.com.com/callback/');
```
but the same issue
if i remove the scope it works with out any problem... 
anybody has a clue what i am doing wrong... the code that i use is a copy and paste from the example with the exemption that i am returning a view and passing the loginurl.
thanks

**Comment by SammyK** [comment]
Are you getting an error message? What version of the package are you using?

**Comment by threeel** [comment]
i am using the latest i believe 
```
    "sammyk/laravel-facebook-sdk": "~2.0@dev",
      "facebook/php-sdk-v4": "~4.1.0@dev",
```
i think i have found the problem. i have appended on the resulting url &display=popup and that seem to fixed the issue. i have been using the login dialog within a captive portal and it was not showing the acceptance of the app or if i already accepted the app it wouldnt do the redirect... after i have set the display param works nice...

**Comment by SammyK** [comment]
Glad you figured it out! You seem to be integrating Facebook login in a very specific way. If a user has already authenticated your app they will not be presented with the authorization dialog again unless they have explicitly deauthorized your app.
