### ISSUE TITLE
All FQB methods? getTokenFromJavascript() doesn't work?

### ISSUE THREAD

**Issue by PanManAms** [SammyK/LaravelFacebookSdk#40]
Hi!
This is probably me doing something wrong: but I try to authenticate a user from the FB.js SDK.
Working with a redirect (without the fb.js SDK) works with:

    $token = Facebook::getTokenFromRedirect();

However, 

    $token = Facebook::getTokenFromJavascript()

doesn't work. The function doesn't exists. What goes wrong here? The frontpage says "all Facebook Query Builder functions are supported". 
I'm using version 1.2 as I'm on laravel 4.2
Thanks!

**Comment by SammyK** [comment]
Hey @PanManAms! There is no `getTokenFromJavascript()` method. If you're trying to obtain an access token from the signed request set in the cookie from the JavaScript SDK, you'll need to [use the Facebook PHP SDK v4.0 directly](https://developers.facebook.com/docs/php/FacebookJavaScriptLoginHelper/4.0.0). It's installed as a dependency so it should be autoloaded for you if you're using composer.

**Comment by PanManAms** [comment]
@SammyK, Thanks for the quick response!.It might 'just' be a documentation issue, but how does this go with, from the frontpage:
*LaravelFacebookSdk is a wrapper for Facebook Query Builder. Any of the Facebook Query Builder methods are accessible via the Facebook facade.*
On the frontpage of the FQB https://github.com/SammyK/FacebookQueryBuilder the `getTokenFromRedirect` and `getTokenFromJavascript` are in the same space. 
Am I missing something? Are the docs wrong?

**Comment by SammyK** [comment]
Ah, I see what you're saying. Are you able to do this?

```php
$token = Facebook::auth()->getTokenFromJavascript();
```

**Comment by PanManAms** [comment]
No, but that's what I would expect.
I get an *Call to undefined method SammyK\LaravelFacebookSdk\LaravelAuthFacebook::getTokenFromJavascript()* error

**Comment by SammyK** [comment]
Ah ha! Gotta play around with this. Thanks for submitting the issue! :)

**Comment by PanManAms** [comment]
Thanks! Let me know if there is anything else I can help with, in testing.

**Comment by PanManAms** [comment]
Any updates on this? I kind of need this functionality, or do I need to use the Facebook PHP libs directly?

**Comment by SammyK** [comment]
No update yet - but I should be able to give it some TLC next week. :)

**Comment by PanManAms** [comment]
FYI, and others running into this: I have this working with the direct FB SDK:
````
use Facebook\FacebookRequest;
use Facebook\FacebookSession;
use Facebook\FacebookJavaScriptLoginHelper;

Route::get('/jstoken', function(){
    FacebookSession::setDefaultApplication($_ENV['FB_APP_ID'], $_ENV['FB_APP_SECRET']);
    $helper = new FacebookJavaScriptLoginHelper();
    try {
        $session = $helper->getSession();
        $newsession=$session->getLongLivedSession();
        $newtoken=$newsession->getToken();
        if ($newsession) {
      // Logged in.
        $request = new FacebookRequest($newsession, 'GET', '/me');
        $response = $request->execute();
        $graphObject = $response->getGraphObject();
        var_dump($graphObject);
        echo json_encode($graphObject);
        //return json_encode($graphObject);    
    }
});
````

But a solution fully within this SDK would be cleaner :)

**Comment by SammyK** [comment]
Hey @PanManAms! I updated the package in 1.3.0 to have an `fqb()` method to access the Facebook Query Builder object directly. So go ahead and update this package and see if you can do something like this:

```php
$token = Facebook::fqb()->auth()->getTokenFromJavascript();
```

Hope that helps! :)

**Comment by PanManAms** [comment]
Thanks!! :+1:
