### ISSUE TITLE
Need Paging information

### ISSUE THREAD

**Issue by jagdeepsinghmundi** [SammyK/LaravelFacebookSdk#41]
I'm fetching new photos uploaded by user.

As facebook has response size limit of 2mb, I cannot pull all the photos in one call because some users have thousands of photos. 

So I need paging information(as provided in javascript response of fb js sdk) to start a new api call to fetch the next set of photos.

Is there any way I can do that using this LaravelFacebookSdk or using FacebookPhpSdk ?

**Comment by jagdeepsinghmundi** [comment]
OK. I found that I can use offset in call.

Just want to know if `->limit(10)->offset(10);` is supported in LaravelFacebookSdk, as I can't find this in docs anywhere.

**Comment by SammyK** [comment]
Yes, but it depends on the version you're using:

## LaravelFacebookSdk 1.2

You can use the FacebookQueryBuilder to paginate.

```php
$res = $fb->object('me/photos')
        ->with(['offset' => $offset])
        ->limit($limit)
        ->get();
```

## LaravelFacebookSdk 2.0

FacebookQueryBuilder was removed from 2.0 and all the functionality falls back to the native Facebook PHP SDK.

```php
$response = $fb->get('/me/photos?limit=5');
$photos = $response->getGraphList();

// Get the next set of 5
$nextPhotos = $fb->next($feed);
```

**Comment by jagdeepsinghmundi** [comment]
OK. Thanks :)

Regards!
Jagdeep Singh
http://jagdeep.me
