### ISSUE TITLE
missing query builder

### ISSUE THREAD

**Issue by davecarlson** [SammyK/LaravelFacebookSdk#42]
Has https://github.com/SammyK/FacebookQueryBuilder been removing in the laravel 5 version ? We have a lot of broken code !

**Comment by SammyK** [comment]
Hey @davecarlson! Correct, FQB was removed in version 2.0 of LaravelFacebookSdk. I also removed lots of other code that didn't need to be in LaravelFacebookSdk and FQB. The main reason for doing this is that a lot of the code has been ported over to the official Facebook PHP SDK it is now much easier to use so using FQB for basic requests isn't necessary.

So where you used to do:

```php
$res = $fb->object('me')->get();
```

You'd just use the native Facebook PHP SDK API:

```php
$res = $fb->get('/me');
```

But if you're making complex nested requests, then FQB is certainly a good call. It would just need to be installed separately in your `composer.json`.

```json
{
    "require": {
        "sammyk/facebook-query-builder": "~2.0@dev"
    }
}
```

I've got FQB mostly working on the new Facebook PHP SDK but it's still in dev mode and I haven't updated the documentation yet. If I have some time this week, I'll give FQB a bit more TLC. :)
