### ISSUE TITLE
Cannot make offline calls to FB using Laravel Queue API

### ISSUE THREAD

**Issue by jagdeepsinghmundi** [SammyK/LaravelFacebookSdk#43]
Trying to fetch user's photos using Laravel Queue API 

But even simple call like this throws `SammyK\FacebookQueryBuilder\FacebookQueryBuilderException`
```php
Facebook::setAccessToken($user->access_token['access_token']);
$user = Facebook::object('me')->fields('id', 'name')->get();
```

I'm using long lived access token here.

What am I doing wrong?

Thanks for help.

**Comment by SammyK** [comment]
What's the error message you're getting?

```php
try {
    $user = Facebook::object('me')->fields('id', 'name')->get();
} catch (SammyK\FacebookQueryBuilder\FacebookQueryBuilderException $e) {
    dd($e->getMessage());
}
```

**Comment by jagdeepsinghmundi** [comment]
it says "Graph returned an error response."

**Comment by SammyK** [comment]
What if you did:

```php
dd($e->getPrevious()->getMessage());
```

**Comment by jagdeepsinghmundi** [comment]
Now I got "Invalid OAuth access token."

**Comment by SammyK** [comment]
Yeah so the access token you're using is not valid for that endpoint. Either because it's the wrong type of token or it has expired. You can [debug it](https://developers.facebook.com/tools/debug/) and find out what's wrong with it.

**Comment by jagdeepsinghmundi** [comment]
"Invalid appsecret_proof provided in the API argument"

Sorry for last post. This is the exception I got.

**Comment by jagdeepsinghmundi** [comment]
Anyways thanks for the help. 

I can debug it now. You are a life saver man. :+1:

**Comment by SammyK** [comment]
No problem. :) Make sure your app secret is correct. It's used to generate the app secret proof. Good luck!
