### ISSUE TITLE
Facade Problem

### ISSUE THREAD

**Issue by anthonyifon** [SammyK/LaravelFacebookSdk#44]
I'm getting the following 
BindingResolutionException in compiled.php line 1067:
Unresolvable dependency resolving [Parameter #0 [ <optional> $message ]] in class Exception
When I try and use the Façade any idea what I might have done wrong

or Is there anyway to make a post 

$status_update = ['link'    => $url,
		'message' => $message,
		'picture'   => $imgurl,
		'name'    => 'More Info',
		'description' => 'Visit site to apply for this job',];
		$response = \Facebook::object('1395318612227381/feed')->with($status_update)->post();

Without the facade

**Comment by anthonyifon** [comment]
Ok I figured I can do $response = $fb->post('1395318612227381/feed', $status_update);
So all good on making my app work in 5 still not sure what the facade issue is though

**Comment by cernicc** [comment]
I have the same BindingResolutionException when trying to run composer update

**Comment by SammyK** [comment]
Oh snap! You're right. This bug has been fixed. So you'll need to `composer update`. Thanks for reporting the bug! :)
