### ISSUE TITLE
Cross-site request forgery validation failed. Required param "state" missing.

### ISSUE THREAD

**Issue by diridam** [SammyK/LaravelFacebookSdk#45]
Hello, 
Anyone seen this ? it happens when obtaining the token from redirect?

**Comment by SammyK** [comment]
Can you post the code that's causing the error? :)

**Comment by dirkpostma** [comment]
Same issue here, using fresh laravel project and exact the example code in README.md

I didn't spend much time finding out what the problem is, but I guess the example code should work out of the box. Here my log to reproduce:

````
$ laravel new testSammyKLaravelFacebookSdk
$ cd testSammyKLaravelFacebookSdk
# edit composer.json
	"sammyk/laravel-facebook-sdk": "~2.0@dev",
        "facebook/php-sdk-v4": "~4.1.0@dev"
$ composer update
# Add provider in config/app.php 
	'SammyK\LaravelFacebookSdk\LaravelFacebookSdkServiceProvider',
$ php artisan vendor:publish --provider="sammyk/laravel-facebook-sdk" --tag="config"
# set app_id and app_secret in config/laravel-facebook-sdk.php
# edit app/Http/routes.php:
   add routes facebook/login and facebook/callback, as in README.md

# set virtual host in MAMP to point to public 
# browse to http://localhost/facebook/login
# Click link
# login in facebook
# Error: "Cross-site request forgery validation failed. Required param "state" missing."

**Comment by diridam** [comment]
It;s a problem which appears only on  Mamp Pro. Didn't managed to figure it
out why, but somehow the session is not saving at that refresh. Otherwise
if you're using the same code in production or in any other environment
except MAMP pro, the error doesn't appear.

On my local i'm commenting the validateCsrf() from Facebook's sdk. (here's
the line: https://github.com/facebook/facebook-php-sdk-v4/pull/297/files)




*Mihai* Tudor
mobile: +4 0721.259.213
email: mihai.tudor@thewizards.ro
find us: www.thewizards.ro;
facebook.com/TheWizardsRo; twitter.com/TheWizardsRo

**Comment by SammyK** [comment]
This seems to be an issue that happens specifically on OS X using MAMP Pro, is that correct? The error means that the session that's set when you generate the login link isn't being "remembered" when the user returns on the callback URL. Are you able to debug the session handling in MAMP Pro to see if you can find an issue with it?

**Comment by diridam** [comment]
Back so solve this issue (it's really irritating and i'm sure that there are more ppl that's getting into this error).
Sammy, help me a bit more on how to debug the session handling

**Comment by kressaty** [comment]
I had this issue as well, using Laravel Homestead. Switched my default session driver to cookie (from file, which is default on L5) and it immediately worked.

**Comment by SammyK** [comment]
Thanks for the info @kressaty! I'm going to spend some time debugging this issue today and hopefully figure out what's going on! :)

**Comment by SammyK** [comment]
Hey @diridam! I'm not able to reproduce this issue on my end.

As far as debugging, we can try and verify it is a session issue. If your sessions aren't being stored properly, this will cause the login to fail.

In the method that generates the login URL, set something in your session:

```php
\Session::put('laravel_session_test', 'Sessions work!');
```

Then in the callback URL where the user is redirected to after they approve or deny the request, try to dump the session value before you try to obtain the access token:

```php
$val = \Session::get('laravel_session_test');

dd($val);
```

If you get a `null` dump, your sessions aren't working properly. Try @kressaty's suggestion of switching the default session driver to something other than "file" and try it again.

I'm going to go ahead and close this for now but if you're still having trouble with it, let me know and we'll do some more debugging.

**Comment by diridam** [comment]
@SammyK! i've tested the sessions and yes, i get a null on that dump. 
So yes, keep it closed. it's a local setup problem. Never had it in staging or prod.

**Comment by SammyK** [comment]
Glad we narrowed that one down! Hope you're able to get your sessions working. :)

**Comment by capitaladot** [comment]
I'm seeing this in an AWS box set to prod. What might be helpful for debugging.?

**Comment by ivus** [comment]
So I've found that this is also isolated to certain version of MAMP Pro. 
What I noticed on older versions was that the session values weren't being set until the page had redirected. My work around from the example code was to do the following.

```php

// Set up a FB session
Route::get('/fblogin', function() {

  \Session::put('laravel_session_test', 'Sessions work!');
  return redirect('/fb/login');

});

// Generate a login URL
Route::get('/fb/login', function(SammyK\LaravelFacebookSdk\LaravelFacebookSdk $fb) {

    // Send an array of permissions to request
    $login_url = $fb->getLoginUrl(['email']);

    echo \Session::get('laravel_session_test');

    // Obviously you'd do this in blade :)
    echo '<a href="' . $login_url . '">Login with Facebook</a>';

});

```

if you also create a test route with the following :

```php

Route::get('/test', function() {
  dd( \Session::all() );
});

```

You can see all the sessions values have been set properly.

**Comment by SammyK** [comment]
Weird. Thanks for the info @ivus!

**Comment by avieln** [comment]
Hey, sorry for bringing this again, but i get the same error on Chrome on android 5. Not all the time, and not all androids, but my lg g3 for example keep getting this error

**Comment by w3nh4o** [comment]
put all your route inside middleware `web`

```
Route::group(['middleware' => ['web']], function () {


});
```
