### ISSUE TITLE
Invalid appsecret_proof provided in the API argument

### ISSUE THREAD

**Issue by ileapaulalexandru** [SammyK/LaravelFacebookSdk#46]
I use Laravel 4.2, so I've installed LaravelFacebookSdk [1.2 branch](https://github.com/SammyK/LaravelFacebookSdk/tree/1.2)

The first error i got was <b>"Graph returned an error response"</b> but after I added a try/catch I got a detailed error:  <b>string(52) "Invalid appsecret_proof provided in the API argument"</b>

My App ID, App Secret and Access Token are good, I checked them 3 times. In my app panel settings/advanced the <b>App Secret Proof for Server API calls</b> option is set to <b>No</b> but I tryed to switch it just to see if it works but with no success.

In composer.json I have something like this: <i>"sammyk/laravel-facebook-sdk": "~1.1" </i>, I've followed all the stepps one by one and I got into this error and don't know what to do.

Can you help me please? Thanks

**Comment by g33kidd** [comment]
Currently I'm having this same error, did you ever figure it out @paulalexandru?

**Comment by paulalexandru** [comment]
Yes I did, but it was long ago and I don't remember what fix I've done. Sorry

**Comment by g33kidd** [comment]
No worries, I forgot to set the App Id and secret, now all is good 👍

**Comment by sooraj20890** [comment]
hey guys how to do you create springjunit test mocks for messenger4j calls like send or onReceiveEvents ?? there isnt much online content on this...in mockit i can when and then the calls in setup but i am not sure how to mock it in spingjunit ofr spring boot applications using messenger4j methods..can anyone suggest some working methods

**Comment by sooraj20890** [comment]
more info on this - om.github.messenger4j.exception.MessengerApiException: Invalid appsecret_proof provided in the API argument
	at com.github.messenger4j.exception.MessengerApiExceptionFactory.create(MessengerApiExceptionFactory.java:29) ~[messenger4j-1.0.0-M3.jar:?]
	at com.github.messenger4j.Messenger.doRequest(Messenger.java:205) ~[messenger4j-1.0.0-M3.jar:?]
	at com.github.messenger4j.Messenger.send(Messenger.java:120) ~[messenger4j-1.0.0-M3.jar:?]

**Comment by sooraj20890** [comment]
i mean if we are just testing arent we supposed to supposed to stop the call messenger.send(payload) and reroute it to our mock method..which is another doubt for me..can we use mock in a test call with SpringJUnit4ClassRunner
