### ISSUE TITLE
uploading photo to facebook

### ISSUE THREAD

**Issue by rapocalypse** [SammyK/LaravelFacebookSdk#48]
Hi Sammy,

  nice job!

I'm looking for any example on how to upload a photo to facebook, using this package, but didn't found nothing about.

Can you hep me with it?

Thanks,

RA

**Comment by diridam** [comment]
Hi, 
Look at SammyK's package as a bridge to facebook's package. If you want to use graph interactions, initialize the fb object and use fb's methods.

For example here's how i delete a request through the api:
```
$fb = App::make('SammyK\LaravelFacebookSdk\LaravelFacebookSdk');
$token = $user->access_token;
$fb->setDefaultAccessToken($token); //client token.
$fb->delete($request_id.'_'.$user_fb_id);
```

for  you i would say that instead ->delete you should use 
```
$fb->post('/me/feed', $object to be posted)

**Comment by SammyK** [comment]
Thanks for chiming in @diridam!

@rapocalypse As @diridam said, the LaravelFacebookSdk is just a wrapper for the Facebook PHP SDK, so you would make most all of your requests just as you would in the PHP SDK.

Are you using Laravel 5? If so, you can just do something like this to upload a photo:

```php
$fb = App::make('SammyK\LaravelFacebookSdk\LaravelFacebookSdk');

$data = [
  'message' => 'My neat photo',
  'source' => $fb->fileToUpload('/path/to/photo.jpg'),
];

try {
  $response = $fb->post('/me/photos', $data, '{user-access-token}');
} catch(Facebook\Exceptions\FacebookSDKException $e) {
  echo $e->getMessage();
  exit;
}

$objectId = $response->getGraphObject();
var_dump($objectId);

echo 'Photo ID: ' . $objectId['id'];
```

**Comment by atefBB** [comment]
Useful ! Thank you !

**Comment by atefBB** [comment]
Hey @SammyK I'm using sammyk/laravel-facebook-sdk v1.3.2, and I copy/paste your code for sharing photos, I face this error : 
`Method fileToUpload does not exist in /home/.../vendor/sammyk/laravel-facebook-sdk/src/LaravelFacebookSdk/LaravelFacebookSdk.php` !
how to solve it? thx !

**Comment by ghost** [comment]
@SammyK Thank you!!!!!!!!!!!!!
