### ISSUE TITLE
Can't generate an access token after it expires

### ISSUE THREAD

**Issue by paulalexandru** [SammyK/LaravelFacebookSdk#49]
I use Laravel 4.2, so I've installed LaravelFacebookSdk [1.2 branch](https://github.com/SammyK/LaravelFacebookSdk/tree/1.2).

What I want to achieve is to get the posts from my facebook page and it works with this:

<b>Facebook::object($my_app_id.'/posts')->fields('message')->get()</b>

So [here](https://developers.facebook.com/) I have a section called My Apps where I can see my App ID and my App Secret which I use here:

<b>Facebook::setAppCredentials($my_app_id, $my_app_secret);</b>

On [this](https://developers.facebook.com/tools/explorer) page I generate an Access Token which I use here:

<b>Facebook::setAccessToken($access_token);</b>

Everything goes well until now, but my access_tocken expres after a while and I can't find a way to generate it again. Curently I store this token into the database because I use it every day.

I tried this:

        try {
            $token = Facebook::getTokenFromRedirect();
            print "success";
            print_r($token);die();
        }
        catch (FacebookQueryBuilderException $e)
        {
            // Failed to obtain access token
            echo 'Error:' . $e->getMessage();
        }

And on the screen I get only the success message printed without any access token. Can you help me with this please?

I added a [stackoverflow question](http://stackoverflow.com/questions/29006950/sammyk-laravelfacebooksdk-cant-obtain-an-access-token) also regarding this.

I do all of this in my controller and I also added this line:

<b>use SammyK\FacebookQueryBuilder\FacebookQueryBuilderException;</b>

**Comment by SammyK** [comment]
Just answered on [StackOverflow](http://stackoverflow.com/questions/29006950/sammyk-laravelfacebooksdk-cant-obtain-an-access-token).
