### ISSUE TITLE
Facebook throws configuration error "Given URL is not allowed by the Application configuration

### ISSUE THREAD

**Issue by mateoprifti** [SammyK/LaravelFacebookSdk#5]
Hello there, first thanks for the package. I am trying to log a user in with facebook using your package but facebook keeps throwing this error. 

Given URL is not allowed by the Application configuration.: One or more of the given URLs is not allowed by the App's settings. It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains.

I know what this means, and i have checked and triple checked that everything is right in my app config at facebook. All the domains and such. I think there must be something with the php sdk v4 thats preventing user login because when i tried login with the JS SDK with the same app config at facebook it worked perfect. I have done research and i can't figure this out. Any help would be greatly appreciated. Thanks.

**Comment by ducnvhn** [comment]
hi Sammy.
First, Thank for your effort on this SDK. 
I've try to follow your example  but still get this error.
my facebook app setting as follow: 

siteURL: http://mysite.com/fblogin

and then in my route file , I added a route for login 
Route::get('/fblogin',function(){
    $login_url = Facebook::getLoginUrl(['email'], 'http://mysite.com/fblogin/addfbuser/');
 return Redirect::to($login_url);
});

and the route for callback
Route::get('/fblogin/addfbuser/',function(){
	/**
     * Obtain an access token.
     */
    try{
        $token = Facebook::getTokenFromRedirect();
    } catch(FacebookQueryBuilderException $e)
    {
        return dd($e->getPrevious()->getMessage());
    }
 //  $user = Facebook::object('me')->fields('id','email')->get();
   return Redirect::to('/fbtest')->with('message',$user);
});

and here the results of dd($e) : string(80) "Invalid redirect_uri: Given URL is not allowed by the Application configuration." 

the URL of the error , I think it included the code: 
http://mysite.com/fblogin/addfbuser?code=AQCN3t0bbsPiGsj41eqFqAGp-sCAvM-cjRMNn0Y6bq7xft3tEiIR6WWI7Dz2QYA3zGZt0uExwrNwqm8XErw2aXYi95M7ik6HM_rZI5yDGKGjbodeHIDEETWvU3ePW2aw7CRX_-LJyITqf23P8jL2coDaGN1D-HGwx0oc2XPLKbcH-Lpx2QK2T1iuSUaT9cY-__QvoIWpR6fkVWsGdDC64v9Zir5gx33h_E909z0l7lPT5230kVe5gxxme7z_NQswi581zfJMxYo7pOZ3DwugR0-qc5r3pGuCD2Cn5SQ-aOZh7o6P4Gfkbu9DiiewwKxbfwF91mb4JObryS5NQQpZRgZN&state=fcc1ae0edd3b2611037f6ced56fa93ce#_=_

**Comment by SammyK** [comment]
The error:

`Invalid redirect_uri: Given URL is not allowed by the Application configuration.`

Indicates that either the URL you're using is not properly set in your [app settings](https://developers.facebook.com/apps) or the `redirect_uri` being used for the login URL and the code-for-token URL are different (most likely what's going on here).

In your Laravel `app/config/app.php` config file, what do you have as the value for `url`? A lot of people leave this as the default value but it could have adverse affects on the URL generation code.

One last thing you can try is manually pass in the callback URL you provided to `getLoginUrl()` (http://mysite.com/fblogin/addfbuser/) to the [`getTokenFromRedirect()` method](https://github.com/SammyK/LaravelFacebookSdk/blob/1.1/src/LaravelFacebookSdk/LaravelFacebookSdk.php#L137):

```php
$token = Facebook::getTokenFromRedirect('http://mysite.com/fblogin/addfbuser/');
```

Try those things out. :)

**Comment by ducnvhn** [comment]
Thank you Sammy, 

I got it working by following your suggestion. Turn out, I have to change URL in app/config/app.php and  app/config/packages/sammyk/laravel-facebook-sdk/config.php => 'default_redirect_uri'.

finally, I can get basic user information . 

I have one question related to this: How do I remember the user after logging them in using your method : Facebook::auth()->login($user); ? is there any option to remember user, so next time won't have to ask them to login again (if they already logged in facebook). 


thank you for your response.

**Comment by SammyK** [comment]
Yay! Glad you got it working!

To mark a user as "logged in" in Laravel, make sure you're saving the user's ID from Facebook in the database. Make sure the database column is an indexed `unsigned BIGINT` because Facebook user ID's are freaking huge.

Then you can search the database for that user based on their Facebook ID to get an instantiation of the user model. Then you just log them in with Laravel's `Auth::login()`:

```php
$user = User::where('facebook_id', '=', $facebook_id])->first();

// Log the user into Laravel
if ($user) {
    Auth::login($user);
}
// If user not in database, create a new record for them and log them in
```

See the "Managing The User's 'Logged In' State With The Web Framework" header in [Facebook Login Flow & Best Practices](https://www.sammyk.me/best-practice-for-facebook-login-with-the-javascript-sdk-and-php-sdk-v4-1) for more info.

**Comment by ducnvhn** [comment]
thank you very much Sammy.
I will give it a try and will surely come back if any problem I may have. hope you dont mind.

regards.

**Comment by SammyK** [comment]
No problem! Good luck! :)

**Comment by rohandaxini** [comment]
Hi @SammyK I am facing same problem "Given URL is not allowed by the Application configuration...." but from my Titanium mobile app for iOS (I did not try Android build yet). I can't figure out what URL should I provide in my `My Apps - Settings - Client OAuth Settings` under my FB account for my app. I tried 6 to 7 different urls and still it does not work. Strange part is it works fine from Web URL and my app correctly Authenticates through Facebook but same isn't working for my Titanium mobile app. I have not yet published my app i.e. the `Status & Review` in my FB account for this app is not yet green or public yet. Would highly appreciate your help in this regard.

**Comment by rohandaxini** [comment]
I forgot to mention @SammyK that I m using "Facebook Login for the Web with the JavaScript SDK" - 
https://developers.facebook.com/docs/facebook-login/login-flow-for-web/v2.0

**Comment by rohandaxini** [comment]
I posted my query here - https://community.appcelerator.com/topic/3102/issue-with-app-js-and-jquery-unable-to-call-methods-between-these-two

I am able to do FB auth using Titanium code in app.js but not using js sdk in custom js function.
