### ISSUE TITLE
Add more examples to the docs

### ISSUE THREAD

**Issue by SammyK** [SammyK/LaravelFacebookSdk#50]
Although the following examples are essentially the same as the native [Facebook PHP SDK doc examples](https://github.com/facebook/facebook-php-sdk-v4/tree/master/docs), people are getting confused.

- [ ] Posting to a user's timeline
- [ ] Batch requests
- [ ] Pagination
- [ ] File Uploads

**Comment by JimmyKosgei** [comment]
I would like to pull a users feed using this

**Comment by diridam** [comment]
@JimmyKosgei 

Try this code:
PS: USER_TOKEN IS THE TOKEN FROM SAMMY's example, the one that's taken out of the user's object at authentication.

```
$fb = \App::make( 'SammyK\LaravelFacebookSdk\LaravelFacebookSdk' );
$fb->setDefaultAccessToken( <USER_TOKEN> );

try {
   $response = $fb->get( '/me/feed');
   dd($response->getGraphObject());
} catch ( \Facebook\Exceptions\FacebookSDKException $e ) {
   dd( $e->getMessage() );
}
```

**Comment by JimmyKosgei** [comment]
I am getting my token from the Javascript SDK. How do I pass it to <USER _TOKEN ABOVE>?

**Comment by diridam** [comment]
ajax? :)

**Comment by JimmyKosgei** [comment]
yes Ajax
