### ISSUE TITLE
How to disable appsecret_proof sending?

### ISSUE THREAD

**Issue by kisPocok** [SammyK/LaravelFacebookSdk#51]
Hi,

I'm in trouble. I would disable appsecret_proof. It's easy with "facebook/facebook-php-sdk-v4" by FacebookSession::enableAppSecretProof(false);

However, v4.1 doesn't have FacebookSession anymore. Is it possible to disable it in LaravelFacebookSdk?

Thanks,
D.

**Comment by SammyK** [comment]
Hey @kisPocok! There isn't a way to disable the `appsecret_proof` in 4.1 or in LaravelFacebookSdk. I'm curious why you need to do that for your particular case. Maybe there's a workaround.

**Comment by kisPocok** [comment]
Hey Sammy! I'm creating an API which is able to save user's Facebook access token. In this case I would like to check the tokens (it's still valid or not). I'm using the same appid / secret as the iOS app (which is requested the token). But I got error code 100 with appsecret_proof error. What is wrong with me? :) Thanks!

**Comment by SammyK** [comment]
Hum... What version of LaravelFacebookSdk are you using? Can you post the code that's causing the error? And are you getting the error on the PHP side or the iOS side?

**Comment by kisPocok** [comment]
Sure, here is the code.
```php
$sdk = App::make('SammyK\LaravelFacebookSdk\LaravelFacebookSdk');
$sdk->setDefaultAccessToken($accessToken);
$response = $sdk->get('/me/permissions')->getDecodedBody();
```
When I run this code I always get "Invalid appsecret_proof provided in the API argument" (code:100)

from composer.json:
```
"require": {
  "sammyk/laravel-facebook-sdk": "~2.0@dev",
  "facebook/php-sdk-v4": "~4.1.0@dev"
}
```

**Comment by kisPocok** [comment]
Grrr. I got it. I made a typo in our Facebook secret code. Sorry and thank you for your reply! Cheers.

**Comment by SammyK** [comment]
Lol. That app secret is pretty important to get right. :) Glad you figured it out! :)

**Comment by kisPocok** [comment]
You were my best Rubber Duck! http://en.wikipedia.org/wiki/Rubber_duck_debugging

**Comment by SammyK** [comment]
Ha! I've never heard of that. That's funny. :D
