### ISSUE TITLE
help : Error validating verification code. Please make sure your redirect_uri is identical to the one you used in the OAuth dialog request

### ISSUE THREAD

**Issue by b3nhysteria** [SammyK/LaravelFacebookSdk#52]
here's my code
route.php : 
Route::get('fby', 'WelcomeController@LogWithFb');
Route::get('/facebook/login', function(SammyK\LaravelFacebookSdk\LaravelFacebookSdk $fb) {
    $login_link = $fb
            ->getRedirectLoginHelper()
            ->getLoginUrl('http://localhost:8000/fby', ['email', 'user_events']);

    echo '<a href="' . $login_link . '">Log in with Facebook</a>';
});

in my WelcomeController : 
use SammyK\LaravelFacebookSdk\LaravelFacebookSdk;
public function LogWithFb(LaravelFacebookSdk $fb) {
//        // Obtain an access token.
        try {
            $token = $fb->getAccessTokenFromRedirect();
        } catch (Facebook\Exceptions\FacebookSDKException $e) {
            dd($e->getMessage());
        }
        // Access token will be null if the user denied the request
        // or if someone just hit this URL outside of the OAuth flow.
        if (!$token) {
            // Get the redirect helper
            $helper = $fb->getRedirectLoginHelper();

            if (!$helper->getError()) {
                abort(403, 'Unauthorized action.');
            }

            // User denied the request
            dd(
                    $helper->getError(), $helper->getErrorCode(), $helper->getErrorReason(), $helper->getErrorDescription()
            );
        }

        if (!$token->isLongLived()) {
            // OAuth 2.0 client handler
            $oauth_client = $fb->getOAuth2Client();

            // Extend the access token.
            try {
                $token = $oauth_client->getLongLivedAccessToken($token);
            } catch (Facebook\Exceptions\FacebookSDKException $e) {
                dd($e->getMessage());
            }
        }

        $fb->setDefaultAccessToken($token);

        // Save for later
        Session::put('fb_user_access_token', (string) $token);

        // Get basic info on the user from Facebook.
        try {
            $response = $fb->get('/me?fields=id,name,email');
        } catch (Facebook\Exceptions\FacebookSDKException $e) {
            dd($e->getMessage());
        }

        // Convert the response to a `Facebook/GraphNodes/GraphUser` collection
        $facebook_user = $response->getGraphUser();

        // Create the user if it does not exist or update the existing entry.
        // This will only work if you've added the SyncableGraphNodeTrait to your User model.
        $user = App\User::createOrUpdateGraphNode($facebook_user);

        // Log the user into Laravel
        Auth::login($user);

        return redirect('/')->with('message', 'Successfully logged in with Facebook');
    }

i just copy paste the example into my fresh laravel 5.. am i doing something wrong with this code?

best regards,

**Comment by b3nhysteria** [comment]
aw sorry my bad, i forgot about configuration laravel-facebook-sdk.php in my folder config..
but now i got problem Class 'Illuminate\Session\Controller' not found..
namespace?
use?

somebody have the same issue with me?

**Comment by SammyK** [comment]
Can you post the full error message and the code that's causing the error?

**Comment by SammyK** [comment]
Going to close this - let me know if you're still having trouble with it! :)

**Comment by amravazzi** [comment]
+1
