### ISSUE TITLE
Doc amendment - VerifyCsrfToken conflict for page tab/canvas

### ISSUE THREAD

**Issue by doginthehat** [SammyK/LaravelFacebookSdk#54]
Just getting setup on a Laravel 5 project, great project, really handy!

The default setup in Laravel 5 has a default middleware to verify the csrf token, which throws an exception in page tab & canvas setup as these use post requests.

Could be worth putting in the documentation.

in `App//Http/Kernel.php`

	protected $middleware = [
		'Clockwork\Support\Laravel\ClockworkMiddleware',
		'Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode',
		'Illuminate\Cookie\Middleware\EncryptCookies',
		'Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse',
		'Illuminate\Session\Middleware\StartSession',
		'Illuminate\View\Middleware\ShareErrorsFromSession',
		//'App\Http\Middleware\VerifyCsrfToken',   // <- turn this off
	];

**Comment by SammyK** [comment]
Excellent point @doginthehat! Thanks for the feedback. I'm going to see if I can create a little bit more elegant way of disabling the CSRF verification for just canvas routes. :)

**Comment by SammyK** [comment]
I added [a bit to the documentation](https://github.com/SammyK/LaravelFacebookSdk#getting-a-tokenmismatchexception-with-canvas-apps). Thanks for pointing this out! :)
