### ISSUE TITLE
Make update/create configurable for FacebookableTrait object 

### ISSUE THREAD

**Issue by ZeKoU** [SammyK/LaravelFacebookSdk#55]
I have a case where I use this package for fetching events and their venues (locations) as a models (Eloquent) from Facebook. My Event model has one Location model. Inside Event, field facebookId gets mapped to ID field from Facebook Graph Event object. Inside Location, field event_id is foreign key to event, and field facebookVenueId is mapped to ID field from Facebook Graph Event Venue object. Whenever I add more events from same host (location), my location gets updated with event_id pointing to last event that I added. Therefore my events get lost. I could have used modeling of type "one location-> many events, but I don't see how that would fix the updates of the same Location object which is caused by this package method 
```php
FacebookableTrait::createOrUpdateFacebookObject()
```

It would be very useful if somehow we could make Eloquent models that use FacebookableTrait to configure whether that model is only updated, created or has currently implemented behavior of type update/create-new. I was looking into static method

```php
/**
     * Like static::firstOrNew() but without mass assignment
     *
     * @param array $attributes
     * @return \Illuminate\Database\Eloquent\Model
     */
    public static function firstOrNewFacebookObject(array $attributes)
    {
        if (is_null($facebook_object = static::firstByAttributes($attributes)))
        {
            $facebook_object = new static();
        }

        return $facebook_object;
    }

```

but don't have ideas how this could be configurable? Actually, truth be told, I am working first time with Laravel, and I am still learning a lot. Anyways, I would be thankful to hear the opinion about the possible implementation or workaround ...

**Comment by ZeKoU** [comment]
Ok, so after some attempts I added this change to the method...

```php
/**
     * Like static::firstOrNew() but without mass assignment
     *
     * @param array $attributes
     * @return \Illuminate\Database\Eloquent\Model
     */
    public static function firstOrNewFacebookObject(array $attributes)
    {
        if(isset(static::$is_create_only) && static::$is_create_only === true){
            $facebook_object = new static();
        } else {
            if (is_null($facebook_object = static::firstByAttributes($attributes)))
            {
                $facebook_object = new static();
            }
        }

        return $facebook_object;
    }
```

As you can see, I am using this static member $is_create_only inside base model classes which are using FacebookableTrait as a flag. It is working, but let's hear some potential enhancements...like I said...to have multiple flags...what do you think?

**Comment by SammyK** [comment]
Thanks for the feedback @ZeKoU!

I'm thinking we could have two new methods on the model that get fired if they exist so that you can handle how the model is created or updated.

Something like this:

```php
class MyModel extends \Illuminate\Database\Eloquent\Model
{
    public function facebookObjectWillCreate($model)
    {
        // Do stuff with $model here

        // Can also return `false` which will prevent the model from creating
        return $model;
    }

    public function facebookObjectWillUpdate($model)
    {
        // Do stuff with $model here

        // Can also return `false` which will prevent the model from updating
        return $model;
    }
}
```

Would that help your particular case?

**Comment by SammyK** [comment]
This feature is [officially implemented](https://github.com/SammyK/LaravelFacebookSdk/tree/1.3#overwriting-model-creation--update-functionality) in 1.3.2. Let me know if you have any trouble with it! :)
