### ISSUE TITLE
Weird error while getting token from redirect

### ISSUE THREAD

**Issue by jdsingh** [SammyK/LaravelFacebookSdk#56]
![Facebook sdk access token problem](http://wstaw.org/m/2015/04/03/snapshot1_1.png)

Came across this error when I try to call getTokenFromRedirect()

```php
        try {
            $token = Facebook::getTokenFromRedirect();

            if (!$token) {
                return false;
            }
        } catch (SammyK\FacebookQueryBuilder\FacebookQueryBuilderException $e) {
            $error = [
                'FQB' => $e->getMessage(),
                'FB_SDK' => $e->getPrevious()->getMessage(),
            ];
            dd($error);
        }

        return $token;
```
I'm using "sammyk/laravel-facebook-sdk": "~1.1" with Laravel 4.2.
What could be the possible reason for this?

Thanks for your help!

**Comment by SammyK** [comment]
I believe this is related to this issue in the main SDK: https://github.com/facebook/facebook-php-sdk-v4/issues/391

I'll have to do some digging to see where this started popping up all of a sudden.

**Comment by jdsingh** [comment]
On localhost it works fine but on server facebook gives this error even when I'm using the same app for both localhost and server.

**Comment by SammyK** [comment]
I think I found the issue. It's due to the way the response is handled in Graph v2.3. Did you recently update to Graph v2.3 or do a `composer update` to pull in the latest PHP SDK 4.0?

I'm working on a patch. :)

**Comment by jdsingh** [comment]
Yeah I did the `composer update` today.

Thanks for patching it up quickly. :smile:

**Comment by SammyK** [comment]
No problem! Here's the [full explanation](https://github.com/facebook/facebook-php-sdk-v4/pull/393) of what is happening. Once the PR gets merged & tagged, you can do another `composer update` and it should work again. :)

**Comment by jdsingh** [comment]
@SammyK Thank you so much :)
