### ISSUE TITLE
Duplicated Values

### ISSUE THREAD

**Issue by marciomansur** [SammyK/LaravelFacebookSdk#57]
Hello!

When I use this code:

			Facebook::setAccessToken( $page_queue->page_token );
			$page  = Facebook::object('me/feed')->get();

I get duplicated values of feed. Is this an error on the package or a something to do with the facebook sdk?

Thanks.

**Comment by SammyK** [comment]
What's the Facebook page you're trying to get the feed from? Can you proved a bit more code context as well?
