### ISSUE TITLE
Unable to obtain access token from Javascript

### ISSUE THREAD

**Issue by harpster604** [SammyK/LaravelFacebookSdk#58]
I'm trying to build an AngularJS app with a Laravel 4.2 backend for the first time, instead of just a Laravel website as I usually do. I have been having a hard time trying to find out the best way to use FB login on top of a regular token based auth system. This package and your article were extremely helpful in almost getting it working.

Currently, I have a token based authentication system working using https://github.com/tappleby/laravel-auth-token and https://github.com/lynndylanhurley/ng-token-auth which is working fine. (I had to modify the ng-auth-token slightly to send back the headers in a specific manner, but the rest worked as is.) So a user can register an account with email/password and login and logout successfully.

Now I tried to add in FB login on top of this using https://github.com/Ciul/angular-facebook (FB JS SDK for Angular) and this package SammyK/LaravelFacebookSdk.

I am able to log in with Facebook (popup comes up if permission not already allowed, or logs in straight if allowed) and this logs me into my auth system correctly. I can also log out of my auth system normally as I did without facebook login. But at this point, if I try to click Login with Facebook again, I get an exception in the response:

```
error: {type: "SammyK\FacebookQueryBuilder\FacebookQueryBuilderException",…}
file: "/home/vagrant/Code/mygreenspace-api/vendor/sammyk/facebook-query-builder/src/Auth.php"
line: 188
message: "Unable to obtain access token from Javascript"
type: "SammyK\FacebookQueryBuilder\FacebookQueryBuilderException"
```

If I refresh the page, I am able to log in again, but if I try to log in without refreshing, the above happens. I am not modifying any of the Facebook cookie data, nor am I logging the user out of Facebook when they log out. Just logging out of my auth token system.

Here is my front end code in Angular:

```javascript
// Facebook login button calls this function
$scope.loginFacebookButton = function() {
    Facebook.getLoginStatus(function(response) {
        console.log(response);
        if(response.status === 'connected') {
            console.log('already connected');
            $scope.authFacebook(); // Call Laravel facebook auth api
        } else {
            console.log('connecting with fb');
            Facebook.login(function(response) {
                $scope.authFacebook(); // Call Laravel facebook auth api
            });
        }
    });
};

$scope.authFacebook = function() {
    $http.get('/api/v1/auth/facebook').
        success(function(data) {
            $auth.user = data.user;
            $rootScope.$broadcast('auth:login-success', data.user);

        }).
        error(function(data) {
            console.log(data);
        });
}
```

Then on the Laravel side, I am pretty much using the code from your documentation as is, with two changes. Using getTokenFromJavascript() instead of getTokenFromRedirect() and I have modified the response at the end to work with my existing auth system:

```php
Route::get('/auth/facebook', function()
	{
		/**
		 * Obtain an access token.
		 */
		try
		{
			// Get token from JS instead of redirect
			$token = Facebook::fqb()->auth()->getTokenFromJavascript();
			//$token = Facebook::getTokenFromRedirect();

			if ( ! $token)
			{
				return Redirect::to('/')->with('error', 'Unable to obtain access token.');
			}
		}
		catch (FacebookQueryBuilderException $e)
		{
			return Redirect::to('/')->with('error', $e->getPrevious()->getMessage());
		}

		if ( ! $token->isLongLived())
		{
			/**
			 * Extend the access token.
			 */
			try
			{
				$token = $token->extend();
			}
			catch (FacebookQueryBuilderException $e)
			{
				return Redirect::to('/')->with('error', $e->getPrevious()->getMessage());
			}
		}

		Facebook::setAccessToken($token);

		/**
		 * Get basic info on the user from Facebook.
		 */
		try
		{
			$facebook_user = Facebook::object('me')->fields('id','first_name','last_name','email')->get();
		}
		catch (FacebookQueryBuilderException $e)
		{
			return Redirect::to('/')->with('error', $e->getPrevious()->getMessage());
		}

		// Create the user if not exists or update existing
		$user = User::createOrUpdateFacebookObject($facebook_user);

		// Log the user into Laravel
		Facebook::auth()->login($user);

		// My code here generates token and sends it to log into my website
		$authToken = AuthToken::create(Auth::user());
		$publicToken = AuthToken::publicToken($authToken);

		return Response::json(array('token' => $publicToken, 'user' => $user->toArray()))->header('X-Auth-Token', $publicToken);
	});
```

I'm not sure why it is unable to get the token information again after the first time. I just realized, I also get the same exception if I do not log the user out of my auth system and try to log in with Facebook twice in a row. Any help is appreciated.

Thanks!

**Comment by SammyK** [comment]
You need to make sure cookies are enabled on the Javascript side of things. I don't use [Ciul/angular-facebook](https://github.com/Ciul/angular-facebook), but looking at the code, you'll need to do something like this:

```javascript
angular.module('app', ['facebook'])
  .config(function(FacebookProvider) {
     FacebookProvider.init({
       appId      : '{your-app-id}',
       cookie     : true,
       version    : 'v2.3'
    });
  });
```

See the [Facebook JavaScript SDK `init()` method docs](https://developers.facebook.com/docs/javascript/reference/FB.init/v2.3) for more info.

**Comment by harpster604** [comment]
I should have specified. The angular FB package already has that enabled by default, and I've even manually set it

```javascript
FacebookProvider.setCookie(true);
```

The cookie does get set for the domain, and login works perfectly fine using the Javascript token the first time, but any subsequent attempts don't work unless the page is refreshed.

**Comment by harpster604** [comment]
I did some debugging on the PHP side and was able to finally catch where the problem happens:

```
object(stdClass)[314]
  public 'error' => 
    object(stdClass)[315]
      public 'message' => string 'This authorization code has been used.' (length=38)
      public 'type' => string 'OAuthException' (length=14)
      public 'code' => int 100
```

This is the response it's getting before throwing the exception so I'm assuming this means the cookie is not being set after the first time on the Javascript side, so it tries to use the same code again and Facebook servers reject it.

I will debug on the Javascript side now. Thanks for your help and thanks for the great work you've done to make things easier for people like me!

**Comment by SammyK** [comment]
> `This authorization code has been used.`

It sounds like your script is trying to reuse the OAuth code that you get on the first go around. You should only need to do this once per session.

I would recommend storing the access token to a session after you've exchanged it for a long-lived access token. Then on the next page load, check if the token exists in the session and use it straight out of the session.

> Thanks for your help and thanks for the great work you've done to make things easier for people like me!

No problem! :)
