### ISSUE TITLE
Facebook post sharing from developer website

### ISSUE THREAD

**Issue by meghna22** [SammyK/LaravelFacebookSdk#60]
I want to post information on facebook from my website and when I hit post button it does not post anything in my profile. I am first time trying this, if you can help that would be great 

Thanks

**Comment by diridam** [comment]
@meghna22 , sammy's package is a wrapper of the facebook's original SDK.

initiate $fb as you would do it to make the oauth and use it to call original SDK's functions.
```PHP
$attachment = [
			'access_token' => $clientToken,  //this one's the one from the oauth.
			'message' => '',
			'name' => ''title,
			'caption' => ''caption',
			'link' => ''app link',
			'actions' => array(
				'name' => 'Take the Bonus now!',
				'link' => ''bonus link from the story''
			),
			'description' => 'description',
			'picture' => 'https://picture link'
		];
$fb->object('me/feed')->with($attachment)->post();
```


@SammyK do i say something wrong here? (not sure if the object() method's still there. this piece of code is from an older app i've made with your package.

**Comment by SammyK** [comment]
@diridam Thanks for chiming in!

Yes, it's just a wrapper for the official Facebook PHP SDK. :) And the code you posted should work with the Laravel 4.2 version. In Laravel 5, `object()` was renamed to `node()`.
