### ISSUE TITLE
 "facebook/php-sdk-v4": "~4.1.0@dev"

### ISSUE THREAD

**Issue by marijang** [SammyK/LaravelFacebookSdk#61]
Composer cant download package

**Comment by marijang** [comment]
Problem 1
    - Installation request for sammyk/laravel-facebook-sdk 2.0.x-dev -> satisfiable by sammyk/laravel-facebook-sdk[2.0.x-dev].
    - sammyk/laravel-facebook-sdk 2.0.x-dev requires facebook/php-sdk-v4 ~4.1.0@dev -> no matching package found.

**Comment by SammyK** [comment]
[Related](https://github.com/facebook/facebook-php-sdk-v4/issues/426). Working on this now. :)

**Comment by SammyK** [comment]
Fixed! Make sure to [update your composer.json](https://github.com/SammyK/LaravelFacebookSdk#installation) with the new version alias to v5:

```
"facebook/php-sdk-v4": "~5.0@dev"
```
