### ISSUE TITLE
graph node field aliases for objects

### ISSUE THREAD

**Issue by tzfrs** [SammyK/LaravelFacebookSdk#62]
Hi,

I'm reading the feed from a page with this SDK like this and want to save data directly into my database

    response   = $this->fbSdk->get('/'. $facebookId . '/posts');
    $response   = $response->getGraphList();
    $posts      = $response->all();
    foreach ($posts as $post) {
        FacebookPost::createOrUpdateGraphNode($post);
    }

However, I'm getting an error 

> ErrorException in helpers.php line 703: preg_replace(): Parameter mismatch, pattern is a string while replacement is an array

This is because I have this line in my `$graph_node_field_aliases` 

`'created_time'  => 'created_at',`

created_time, however, is a DateTime object. How would I save this into my database.

**Comment by tzfrs** [comment]
Also,

if I have an additional custom field in the database. What would I need to do, do save this also to the database? Or is the `createOrUpdateGraphNode` method just for responses that can be saved directly into the db without additional data?

**Comment by SammyK** [comment]
Thanks for submitting this issue! I'll try to get a fix for this this week. :)

> if I have an additional custom field in the database. What would I need to do, do save this also to the database?

I should probably create an interface for this as well.

**Comment by emitategh** [comment]
Hi! is it okay to?

--- add a protected static variable like:  $fb_graph_fillable = ['name', 'email', 'facebook_id'];

-- and modify SyncableGraphNodeTrait function  mapGraphNodeFieldNamesToDatabaseColumnNames as: 

public static function mapGraphNodeFieldNamesToDatabaseColumnNames(Model $object, array $fields)
    {
        foreach ($fields as $field => $value) {
            if (isset(static::$fb_graph_fillable[$field])){
                $object->{static::fieldToColumnName($field)} = $value;
                
            }
        }
    }

**Comment by SammyK** [comment]
This issue [has been addressed](https://github.com/SammyK/LaravelFacebookSdk#date-formats). Thanks for submitting the issue! :)
