### ISSUE TITLE
Error in saving graph user Profile Pic/gravatar url

### ISSUE THREAD

**Issue by akubudoy** [SammyK/LaravelFacebookSdk#63]
Hi. is it possible to save the profile pic url to the database? 
i tried using 

```php
// Get basic info on the user from Facebook.
$response = $fb->get('/me?fields=id,name,email,picture{url}');

// Convert the response to a `Facebook/GraphNodes/GraphUser` collection
$facebook_user = $response->getGraphUser();

// Create the user if it does not exist or update the existing entry.
$user = App\User::createOrUpdateGraphNode($facebook_user);


```
but when i tried to save it on the database im having errors and its stored as "Array" .

can you help me pls?

**Comment by SammyK** [comment]
This is a feature [I added to the 1.3 branch](https://github.com/SammyK/LaravelFacebookSdk/tree/1.3#nested-field-mapping), but I haven't added it to 2.0 yet. I'll add it to the TODO list. :)

**Comment by SammyK** [comment]
This feature [has been added](https://github.com/SammyK/LaravelFacebookSdk#nested-field-mapping). Thanks for submitting the issue! :)
