### ISSUE TITLE
How to avoid requesting authorization after the access token for a user expires?

### ISSUE THREAD

**Issue by ayatojhans** [SammyK/LaravelFacebookSdk#64]
I'm trying to display a user's public feed in a website, much like the official widget. So let's say I make him go through the OAuth flow, he grants permission for `user_posts`, I get a token back, and I'm able to call `/{user-id}/statuses` because I want to display his statuses.

First of all, is all of that really neccesary? I've achieved a similar goal with Twitter and Instagram, without the need of login the user and granting permission for public data. Is there no other way to get a user's latest posts?

If I have a long-lived access token, it's still going to expire eventually. I don't want the user re-logging every time the token expires. How can I avoid this?

**Comment by SammyK** [comment]
> he grants permission for user_posts, I get a token back, and I'm able to call /{user-id}/statuses because I want to display his statuses.

You don't need any special permissions to view the public posts as long as you have the user's ID. Any valid access token should work for public data on most endpoints like that. For example I can use my own user access token to see Zuk's public status updates:

```
GET /4/statuses
```

The key is to obtain the user's ID at some point.

> If I have a long-lived access token, it's still going to expire eventually.

You could use an app access token, but only if the API calls are going to be made on the server-side. The app access token contains the app secret so you don't want that bad boy exposed to the world.

Hope that helps!

**Comment by ayatojhans** [comment]
I tried using an app access token (only used by my PHP code). I called `https://graph.facebook.com/oauth/access_token?client_id=MY_APP_ID&client_secret=MY_APP_SECRET&grant_type=client_credentials` and I saved the app access token.

Then:
```php
new FacebookRequest(
    FacebookSession('MY_APP_ACCESS_TOKEN'),
    'GET',
    '/4/statuses'
);
```
When I return the Graph object, it's empty. In fact, I expected it. According to the docs:
> Your app needs `user_posts` permission from the person who created the post or the person tagged in the post.

Besides the app access token, I also tried with my own user access token, same thing :(

I know the user ID, got it from here: http://findmyfacebookid.com/

**Comment by SammyK** [comment]
> I tried using an app access token

Your app access token can be generated by just concatenating your app ID and secret:

```
app-id|app-secret
```

> I know the user ID, got it from here: http://findmyfacebookid.com/

User ID's are app-scoped starting when Graph 2.0 was released. So you'll want to use your app to obtain the user's ID.

Check out the [Graph explorer](https://developers.facebook.com/tools/explorer?method=GET&path=4%2Fstatuses) to play with the endpoint some.

**Comment by ayatojhans** [comment]
Where do I need to concatenate the app ID and secret? I'm using the explorer, pasted my app access token, still returns an empty array.

**Comment by ayatojhans** [comment]
Ignoring the SDK and the PHP code, this is what I've done:
- Went to my App page, grabbed `app_id` and `app_secret`.
- Got my app access token from `https://graph.facebook.com/oauth/access_token?client_id=app_id&client_secret=app_secret&grant_type=client_credentials`
- Tried to fetch the data from `https://graph.facebook.com/4/feed?access_token=my_app_access_token`

Empty array.
