### ISSUE TITLE
Unsupported GET request - Albums edge

### ISSUE THREAD

**Issue by 0x1ad2** [SammyK/LaravelFacebookSdk#65]
Hi Sammy,

You package is working like a charm but today we encountered a strange issue.
We've a customer that has a **facebook_id** that's valid and also has photo albums available on their account. 

If I try to GET the albums through the Graph API Explorer everything is going fine and I'll get the result that I want: https://developers.facebook.com/tools/explorer/145634995501895/?method=GET&path=277629418940547%2Falbums&

But If I use your package Graph API will throw the following error.
> string(114) "Unsupported GET request. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api"

There are a couple of thousands customers available and this is the only one (for now) who's having the problem.

With the following code example you could reproduce the error, and if you enable the line underneath it will so you a working result.

```php
try
{
    // Pub - Café Riviera
    $pubAlbums = \Facebook::object('277629418940547/albums')->get();

    // Pub - Jantjes Verjaardag
    // $pubAlbums = \Facebook::object('149457241787576/albums')->get();

    return $pubAlbums;
}
catch (FacebookQueryBuilderException $e)
{
    dd($e->getPrevious()->getMessage());
}
```

**Comment by 0x1ad2** [comment]
The **root_edge** object in your get() method also is the same if I print it in both situations.

Situation 1 (error)

```php
object(SammyK\FacebookQueryBuilder\RootEdge)#741 (6) {
  ["is_root":protected]=>
  bool(true)
  ["compiled_values":protected]=>
  array(0) {
  }
  ["name"]=>
  string(22) "277629418940547/albums"
  ["fields"]=>
  array(0) {
  }
  ["modifiers"]=>
  array(0) {
  }
  ["limit"]=>
  int(0)
}
```

Situation 2 (working)
```php

object(SammyK\FacebookQueryBuilder\RootEdge)#741 (6) {
  ["is_root":protected]=>
  bool(true)
  ["compiled_values":protected]=>
  array(0) {
  }
  ["name"]=>
  string(22) "149457241787576/albums"
  ["fields"]=>
  array(0) {
  }
  ["modifiers"]=>
  array(0) {
  }
  ["limit"]=>
  int(0)
}
```

**Comment by 0x1ad2** [comment]
@SammyK I just debugged the execute() method and copied both url's (the are nearly identical except for the **facebook_id**) containing the request and my **access_token** & **appsecret_proof** and paste them in my browser, turns out it's going wrong at Facebook's side (maybe you could investigate it with me?).

**Comment by 0x1ad2** [comment]
@SammyK It has something to do with permissions, I think they restricted the ability to view photo albums from an external source in some way. I'll update you once I've found the solution.

**Comment by SammyK** [comment]
Glad you figured out the source of the issue! I'd recommend [submitting a bug report](https://developers.facebook.com/bugs) with all the relevant info. Facebook is pretty good at fixing bugs on the Graph API. :)
