### ISSUE TITLE
Post Message To Page's Wall

### ISSUE THREAD

**Issue by dieka2501** [SammyK/LaravelFacebookSdk#68]
Hello, i try to post message to page's wall.
based on https://developers.facebook.com/docs/graph-api/reference/v2.3/page/feed 
But always get error (#200) Insufficient permission to post to target on behalf of the viewer"

This is my post code 
Facebook::object('{page_id}/feed')->with($status_update)->post()
if i change with
Facebook::object('me/feed')->with($status_update)->post()
it's working well, but it post to my wall

And this is my default scope config 
 'default_scope' => ['manage_pages','email','public_profile','user_friends','publish_actions','publish_pages'],

Anyone can explain why? Is there something i missing?

**Comment by SammyK** [comment]
The access token you're using to publish the post must be a valid user or page access token with the proper permissions.

Has the page you're trying to post to been published yet or is it still private? Have you tried to post to the page using the [Graph API Explorer](https://developers.facebook.com/tools/explorer)?

**Comment by dieka2501** [comment]
Yes, i had post using Graph API Explorer and it's working well, the message appear on page's wall.

how to test the token, to make sure the token is valid?

**Comment by SammyK** [comment]
> how to test the token, to make sure the token is valid?

You can debug the token by using the [`/debug_token` endpoint](https://developers.facebook.com/docs/graph-api/reference/v2.3/debug_token).

**Comment by dieka2501** [comment]
Hello, my website can posting to page's wall after i call user account object 
Facebook::object('me/accounts')->get();
(https://developers.facebook.com/docs/facebook-login/access-tokens#pagetokens) and use access_token from response that API/function

Thanks for your help :)

**Comment by SammyK** [comment]
Ah yes - that would be a page access token. Glad you figured it out! :)
