### ISSUE TITLE
Flow

### ISSUE THREAD

**Issue by jrean** [SammyK/LaravelFacebookSdk#7]
Hi @SammyK,
Thank you for your amazing work!
If you don't mind I would ask you a couple of questions.

I read your articles on https://www.sammyk.me
I read your documentation.
I'm practicing on a personal project hosted on my localhost running with Laravel 4.2.
My Facebook app is well configured.

So I have a page "/login" which displays 3 social login buttons "1)Facebook" ; "2)Google" ; "3)Twitter"

When I click on "1)Facebook" it redirects to "/auth/facebook" and starts the login flow.

What is the purpose of the following line?

```PHP
Facebook::setAccessToken($token);
```

Once this line is executed, I can perform FbGraph requests.
What happens if user go to another page? For example "/profile"
On this route, I need to perform a request on the FbGraph again.

For now, if I try it says:
```PHP
Method Facebook\Entities\AccessToken::__toString() must return a string value"
```

What is the flow I'm missing from the first steps? I guess I need to store the token to the session then retrieve it from the route /profile to be able to perform requests? I tought it was the work done by setAccessToken method! Is it?

Can you please give me some directions about the flow to follow? The goal of the token is to not be asked at each request. What is the best way to store it and use it.

With best regards,

J.

**Comment by tvmaly** [comment]
Hey Sammy,  I really appreciate all the work you have done with LaravelFacebookSdk.   I was not sure how to message you on github.   I just had a general architecture question.  I have the sdk up and working, and I am able to get the oauth working.  My issue is that I designed my user table to require a username and password.  I really do not have good values for these two columns given what is returned from facebook.  What would you recommend for this case where one would want to support regular site login and login with facebook?

**Comment by SammyK** [comment]
Hey @tvmaly! I just wrote a blog post on [Facebook login flow](https://www.sammyk.me/best-practice-for-facebook-login-with-the-javascript-sdk-and-php-sdk-v4-1). You can skip down to the header, "Managing The User's 'Logged In' State With The Web Framework" and start reading from there. That should hopefully address your question. :)

**Comment by tvmaly** [comment]
Thanks Sammy for the blog post.  -Ty

**Comment by SammyK** [comment]
Glad to help! :)

**Comment by tvmaly** [comment]
I got it all working now,  I ended up making my password field nullable, and I insert the fb id into the username field.  It is a little bit of a hack, but it does what I want it to do.

**Comment by SammyK** [comment]
Yay! Glad you got it rocking! :)
