### ISSUE TITLE
get events from a page "Unable to convert response from Graph to a GraphNode" 

### ISSUE THREAD

**Issue by BriBarthelemy** [SammyK/LaravelFacebookSdk#73]
Hello,
I have an issue to covert events from page-id:

 $fb = App::make('SammyK\LaravelFacebookSdk\LaravelFacebookSdk');
  $fb->setDefaultAccessToken('token-string-xxx');
    
    // Get basic info on the user from Facebook.
    try {
        $response = $fb->get('/{page-id}/events');
        
    } catch (Facebook\Exceptions\FacebookSDKException $e) {
        dd($e->getMessage());
    }
    //$response = $request->execute();
    $graphObject = $response->getGraphObject();

Always same answer : 
 FacebookSDKException in GraphNodeFactory.php line 224:
 Unable to convert response from Graph to a GraphNode because the response looks like a   GraphEdge. Try using GraphNodeFactory::makeGraphEdge() instead.

I've try as you see here : https://developers.facebook.com/docs/graph-api/reference/page/events/

Do I do it wrong?
Thanks for your help.

**Comment by SammyK** [comment]
> Do I do it wrong?

Yes. :) But you're really close!

The `/{page-id}/events` endpoint is [an edge](https://developers.facebook.com/docs/graph-api/reference/page/events) and returns multiple [Event nodes](https://developers.facebook.com/docs/graph-api/reference/v2.3/event). So you can't use `getGraphObject()` on the response since that method tries to convert the response into a single Graph node collection. You have to use `getGraphList()` (which is now `getGraphEdge()`).

So just change this:

```php
$graphObject = $response->getGraphObject();
```

To this:

```php
// If you have an old dev version of the official SDK
$graphEdge = $response->getGraphList();
// Or if you have the latest dev version of the official SDK
$graphEdge = $response->getGraphEdge();
```

**Comment by upwebdesign** [comment]
One question I have about this is how do you request more pages after you get the first 10 results?

**Comment by upwebdesign** [comment]
I assume it is something similar to this, but I always get null. Here is what I suspect we do for paging:

$response = $response->getGraphEdge();
$response = $this->fb->previous($response); OR
$response = $this->fb->next($response);

Am I on track with this?

**Comment by SammyK** [comment]
@upwebdesign Yes, you would pass the results from `getGraphEdge()` to `next()` and `previous()`. If it returns `null`, that means there are no more results.

**Comment by seetozenith** [comment]
I wrote below these code:::
       $request = new Facebook\FacebookRequest(
	  $session,
	  'GET',
	  '/'.$user_id.'/friends'
	);
	$response = $request->execute();
	$graphObject = $response->getGraphObject();

Error:: **Fatal error: Call to undefined method Facebook\FacebookRequest::execute()**

Any suggestion please..............

**Comment by jaketoolson** [comment]
@seetozenith you are calling the facebook SDK directly... why aren't you calling the GET request using this package's SDK wrapper?

**Comment by themood54** [comment]
your not doing it wrong, all the code on facebook is missing parts for the .php the only one that works from the facebook dev is javascript and even that is missing parts they must have done it on purpose so only true developers would be able to get it going.
