### ISSUE TITLE
IOC Container does not work for Lavavel 5.1

### ISSUE THREAD

**Issue by imtommychan** [SammyK/LaravelFacebookSdk#77]
When I apply it at controller level, it return the error:
"ReflectionException in RouteDependencyResolverTrait.php line 57:
Class App\Http\Controllers\SammyK\LaravelFacebookSdk\LaravelFacebookSdk does not exist"

public function show($id, SammyK\LaravelFacebookSdk\LaravelFacebookSdk)
{
...
}

**Comment by SammyK** [comment]
> public function show($id, SammyK\LaravelFacebookSdk\LaravelFacebookSdk)

You need to add the `$fb` variable to your method signature:

```php
public function show($id, SammyK\LaravelFacebookSdk\LaravelFacebookSdk $fb)
```
