### ISSUE TITLE
Add support for Laravel 5.1 LTS

### ISSUE THREAD

**Issue by d-a-n** [SammyK/LaravelFacebookSdk#78]
@taylorotwell removed some methods from Laravel 5.1 that LaravelFacebookSdk is using. This will break methods like `createOrUpdateGraphNode`. 

```
BadMethodCallException in Builder.php line 1992:
Call to undefined method Illuminate\Database\Query\Builder::firstByAttributes()
```
Change log:
http://comparabl.com/upgrade/laravel-framework/v5.0.33/v5.1.0

**Comment by SammyK** [comment]
I've created a new 3.0 branch for Laravel 5.1 stuff. This issue is being worked on in #74. I'll keep you posted. :)

**Comment by SammyK** [comment]
Laravel 5.1 support has been added to [3.0](https://github.com/SammyK/LaravelFacebookSdk/tree/3.0). Make sure to update your `composer.json` file:

     "sammyk/laravel-facebook-sdk": "~3.0@dev"

**Comment by d-a-n** [comment]
@SammyK: great, thanks a lot.
