### ISSUE TITLE
Using IoC container from a constructor

### ISSUE THREAD

**Issue by tzfrs** [SammyK/LaravelFacebookSdk#81]
Hi,

I have a cronjob that get's data from Facebook. Because I needed some more methods than your SDK provided I wrote a wrapper that extends your class like this 

`class FacebookWrapper extends LaravelFacebookSdk`

As you described in your readme.md I would need to do it like this

    class FooClass {
        public function __construct(SammyK\LaravelFacebookSdk\LaravelFacebookSdk $fb) {
           // . . .
        }
    }

But when I'm doing it like that, and want to create a new object

`$fb = new FacebookWrapper`

I'm getting the error from my IDE that required parameter `$fb` is missing. It seems like I'm failing somehow to do the correct implementation. What is the right way to implement it? This is the class

    use SammyK\LaravelFacebookSdk\LaravelFacebookSdk;
    use Symfony\Component\HttpFoundation\Response;
    
    /**
     * Class FacebookWrapper
     * @package App\Wrapper
     * @version 1.0 
     */
    class FacebookWrapper extends LaravelFacebookSdk
    {
        public function __construct(LaravelFacebookSdk $fb)
        {
        }

        public function customMethod()
        {
        }
    }

And this is how I want to create an object

`$facebookData = (new FacebookWrapper)->customMethod();`

**Comment by SammyK** [comment]
You want to either extend the class or inject the instance, not both. I recommend injecting the instance:

```php
use SammyK\LaravelFacebookSdk\LaravelFacebookSdk;
use Symfony\Component\HttpFoundation\Response;

class MyCustomFacebook
{
    private $fb;
    public function __construct(LaravelFacebookSdk $fb)
    {
        $this->fb = $fb;
    }

    public function customMethod()
    {
        // Do stuff with $this-fb here
    }
}
```
