### ISSUE TITLE
App ID not supplied in config

### ISSUE THREAD

**Issue by rajgaurav1** [SammyK/LaravelFacebookSdk#84]
I've published the config file with app id and app secret, but I get the following error

FacebookSDKException in Facebook.php line 133:
Required "app_id" key not supplied in config and could not find fallback environment variable "1621623694787935"

**Comment by SammyK** [comment]
Are you editing the Facebook.php class directly with your app ID and secret? You shouldn't make any modifications to any of the source files. Make sure you're injecting the app ID and secret via the constructor when you instantiate it:

```php
$fb = new Facebook\Facebook([
    'app_id' => 'your-app-id',
    'app_secret' => 'your-app-secret',
]);
```

**Comment by SammyK** [comment]
Ooops - I just realized you posted this in LaravelFacebookSdk and not the main Facebook PHP SDK repo. Lol. How are you installing, configuring & grabbing an instance of the class?

**Comment by SammyK** [comment]
Let me know if you're still having issues with this!

**Comment by jkirkby91** [comment]
Can we reopen this, as im experiencing the same issue, following the guides in README for facebook redirect login, even though app_id && app_secret are in the published laravel-facebook-sdk and in .env i get and error the same as OP

**Comment by maungyehtunzaw** [comment]
Call to undefined method Facebook\Facebook::api() ? plz

**Comment by hfuccillo** [comment]
Same issue here, please reopen the issue.

**Comment by hfuccillo** [comment]
In order to avoid modifying the source code, I put this code in facebook.php config file:

```
<?php
putenv('FACEBOOK_APP_ID='. env('APP_FB_ID'));
putenv('FACEBOOK_APP_SECRET='. env('APP_FB_SECRET'));

return [
	'AppId' => env('APP_FB_ID'),
	'AppSecret' => env('APP_FB_SECRET')	
];
```
I'm not proud of this fix, but it works.

**Comment by SammyK** [comment]
What version of PHP are you using?

**Comment by orgilkh** [comment]
Hello, I am having same issue! My version is:
Apache/2.4.9 (Win64) PHP/5.5.12 Server at localhost Port 8080

**Comment by drahosistvan** [comment]
I had the same issue first, but I realized, that it was fully my mistake.
I touched the configuration file, and edited like this:
```
'facebook_config' => [
        'app_id' => env('123456'),
        'app_secret' => env('adsf'),
        'default_graph_version' => 'v2.5',
        //'enable_beta_mode' => true,
        //'http_client_handler' => 'guzzle',
    ],
```
That's why, the system tried to fetch a wrong environment variable :dancer:

**Comment by trevorgehman** [comment]
I'm also experiencing this issue.

**Comment by SammyK** [comment]
It sounds like people are editing the config file for the app ID and secret. You should leave it as is:

```
'facebook_config' => [
        'app_id' => env('FACEBOOK_APP_ID'),
        'app_secret' => env('FACEBOOK_APP_SECRET'),
        'default_graph_version' => 'v2.5',
    ],
```

And add the following to your `.env` file:

```
FACEBOOK_APP_ID=your-app-id
FACEBOOK_APP_SECRET=your-app-secret
```

**Comment by trevorgehman** [comment]
My issue ended up being unrelated to this repo. I was unintentionally directly instantiating the `\Facebook\Facebook` class, which led to the issue.

**Comment by SammyK** [comment]
Ah! Glad you figured it out! :)

**Comment by MarcelDoesCode** [comment]
Hello, I have the same error and what @trevorgehman seems to apply to me, because I am initializing the facebook api in a service provider:

```
public function boot()
    {
        self::$fb = new Facebook([
            'app_id' => env('FACEBOOK_APP_ID'),
            'app_secret' => env('FACEBOOK_APP_SECRET'),
            'default_graph_version' => 'v2.5',
            'default_access_token' => env('FACEBOOK_ACCESSTOKEN')
        ]);
    }
```

I never had problems with it. I haven't worked on the code for two weeks and now I wonder why it does not work anymore and also what's the problem with  

> directly instantiating the \Facebook\Facebook class

**Comment by SammyK** [comment]
@MarcelDoesCode The package comes with a service provider already. See: https://github.com/SammyK/LaravelFacebookSdk#service-provider
