### ISSUE TITLE
Support for updating the app id/secret at run time

### ISSUE THREAD

**Issue by adulion** [SammyK/LaravelFacebookSdk#88]
Might not be useful for everyone but-

I have built an app for the management of multiple facebook apps and it would be great if there was a set method in the code to allow us to switch app ID/secrets at run time

**Comment by pionl** [comment]
+1

**Comment by Noodlewitt** [comment]
yes, I would also love to be able to do this. +1

**Comment by yellowhite** [comment]
+1

**Comment by SammyK** [comment]
There is an open PR for this in #92

**Comment by adulion** [comment]
i ended up writing my own facebook driver with the Facebok sdk version 4

**Comment by SammyK** [comment]
This feature [has been added](https://github.com/SammyK/LaravelFacebookSdk#working-with-multiple-apps). Thanks! :)
