### ISSUE TITLE
Question: Branches 2 or 3 with Laravel 4?

### ISSUE THREAD

**Issue by davout1806** [SammyK/LaravelFacebookSdk#89]
Because of https://github.com/SammyK/LaravelFacebookSdk/issues/27#issuecomment-89432112 is it possible to use branch 2.0 or 3.0 with the Laravel 4.2?

Thanks.

**Comment by SammyK** [comment]
Unfortunately the way packages tie into Laravel changed in Laravel 5.0 so it's not possible. :/
