### ISSUE TITLE
About Facebook::getTokenFromRedirect()

### ISSUE THREAD

**Issue by naupaw** [SammyK/LaravelFacebookSdk#9]
i read about this instruction

> there is a wrapper for `getTokenFromRedirect()` that defaults the callback URL to whatever is set in the config.

But when i set `redirect_uri` in config, the function `Facebook::getLoginUrl()` run normally with redirect_uri from config file

And when i using `getTokenFromRedirect()` without parameter, i getting error

> Unable to obtain access token from redirect facebook

But if i set the paramter like this `Facebook::getTokenFromRedirect(url('/whatever/link/'));`

it's return token with experies date.

**Comment by robertlagrant** [comment]
@samm

**Comment by SammyK** [comment]
Glad you figured it out @robertlagrant!
