### ISSUE TITLE
Error in documentation: callback_uri

### ISSUE THREAD

**Issue by borys-p** [SammyK/LaravelFacebookSdk#90]
Hi,

Documentation says that:
> There is a wrapper method for getRedirectLoginHelper()->getAccessToken() in LaravelFacebookSdk called getAccessTokenFromRedirect() that defaults the callback URL to whatever the current URL is.

But this method defaults to `laravel-facebook-sdk.default_redirect_uri` config value.

**Comment by SammyK** [comment]
Fixed! Thanks. :)
