### ISSUE TITLE
Sessions handling

### ISSUE THREAD

**Issue by rsands2801** [SammyK/LaravelFacebookSdk#91]
Is this project supporting laravels sessions or is it using $_SESSION like the default facebook sdk does?

**Comment by SammyK** [comment]
[Laravel sessions](https://github.com/SammyK/LaravelFacebookSdk/blob/3.0/src/LaravelFacebookSdk/LaravelPersistentDataHandler.php).

**Comment by rsands2801** [comment]
@SammyK sorry i must have been blind when i looked at the code!

**Comment by SammyK** [comment]
No worries :)
