### ISSUE TITLE
Auth with Sentry

### ISSUE THREAD

**Issue by g77** [SammyK/LaravelFacebookSdk#94]
I have implemented your package but I can't make a login with Facebook::auth() because I'm using Sentry for user login/registration.
How to login with Sentry and LaravelFacebookSdk?

**Comment by SammyK** [comment]
I don't use Sentry but I imagine you just need to find the user model by their Facebook ID and then use `Sentry::login()` to log them in. As long as your `User` model implements `Cartalyst\Sentry\Users\UserInterface` you should be able to do this:

```php
// Find the user using the their Facebook id
$user = User::where('facebook_id', 4)->first();

// Log the user in
Sentry::login($user, false);
```
