### ISSUE TITLE
Config File 'default_redirect_ui'

### ISSUE THREAD

**Issue by mbarwick83** [SammyK/LaravelFacebookSdk#96]
Config file values 'default_redirect_uri' and 'default_scope' are being overwritten when you `composer update`...

This is a huge inconvenience, when adding unrelated packages and having to run this function.

**Comment by SammyK** [comment]
Doing a `composer update` shouldn't affect the config files. What's your require line look like for the LaravelFacebookSdk in your composer.json? And what version of Laravel are you on?

**Comment by SammyK** [comment]
Hey @mbarwick83! Let me know if you're still having an issue with this. :)
