### ISSUE TITLE
Lumen Support

### ISSUE THREAD

**Issue by thiagof** [SammyK/LaravelFacebookSdk#97]
For the sake of using some of the components, lumen support should be managed.

**Comment by irazasyed** [comment]
You could use this package: https://github.com/irazasyed/larasupport

It'll add support in Lumen to use any Laravel package.

**Comment by SammyK** [comment]
I'm going to see what needs to be done to support Lumen and let you know. :)

**Comment by linkthrow** [comment]
I have forked this project and added Lumen support for anyone who is interested:
https://github.com/linkthrow/LumenFacebookSdk

**Comment by SammyK** [comment]
Updated for Lumen support in latest tag. :)
