### ISSUE TITLE
How to post a like to a post using the 5.1 code

### ISSUE THREAD

**Issue by responsemktg** [SammyK/LaravelFacebookSdk#98]
Previously i have seen code like:
`$response = Facebook::object('/{post id}/likes' )->post(); `

But I am not entirely sure how this is possible from the new version. Is this possible?

**Comment by NightZpy** [comment]
Can you share the code for that?

**Comment by irazasyed** [comment]
```php
$response = Facebook::post('/{post id}/likes');
$graphNode = $response->getGraphNode();
```

**Comment by SammyK** [comment]
Thanks for the help @irazasyed ! :)

**Comment by irazasyed** [comment]
@SammyK No problem :)
